<h1>Importing the libraries needed</h1>

In [516]:
import pandas as pd

In [517]:
import numpy as np

In [518]:
import matplotlib as mlt

<h2 clr="blue">Reading the csvs</h2>

In [520]:
dw1to12=pd.read_csv("dataset/01_District_wise_crimes_committed_IPC_2001_2012.csv")

In [521]:
dw13=pd.read_csv("dataset/01_District_wise_crimes_committed_IPC_2013.csv")

In [522]:
dw14=pd.read_csv("dataset/01_District_wise_crimes_committed_IPC_2014.csv")

In [523]:
pc1to12=pd.read_csv("dataset/17_Crime_by_place_of_occurrence_2001_2012.csv")

In [524]:
pc13=pd.read_csv("dataset/17_Crime_by_place_of_occurrence_2013.csv")

In [525]:
pc14=pd.read_csv("dataset/17_Crime_by_place_of_occurrence_2014.csv")

<h2>Mergining the first two csv</h2>

In [528]:
df = pd.concat(
    map(pd.read_csv, ['dataset/01_District_wise_crimes_committed_IPC_2001_2012.csv', 'dataset/01_District_wise_crimes_committed_IPC_2013.csv']), ignore_index=True)

In [731]:
df

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,92,...,30,1131,16,149,34,175,0,181,1518,4154
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,106,...,69,1543,7,118,24,154,0,270,754,4125
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,118,...,38,2088,14,112,83,186,0,404,1262,5818
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,50,...,23,795,17,126,38,57,0,233,1181,3140
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,98,...,41,1244,12,109,58,247,0,431,2313,6507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,Lakshadweep,LAKSHADWEEP,2013,0,0,0,2,0,2,0,...,1,5,0,1,0,0,0,0,18,40
9836,Lakshadweep,ZZ TOTAL,2013,0,0,0,2,0,2,0,...,1,5,0,1,0,0,0,0,18,40
9837,Puducherry,KARAIKAL,2013,6,3,0,6,0,6,6,...,3,160,1,1,1,1,0,32,329,643
9838,Puducherry,PUDUCHERRY,2013,25,8,2,11,0,11,76,...,13,555,0,11,7,7,0,206,1464,3113
9839,Puducherry,ZZ TOTAL,2013,31,11,2,17,0,17,82,...,16,715,1,12,8,8,0,238,1793,3756

In [534]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [732]:
dw14.columns=dw14.columns.str.upper()

In [540]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',
       'ATTEMPT TO COMMIT CULPABLE HOMICIDE', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE', 'RAPE_OTHERS',
       'ATTEMPT TO COMMIT RAPE', 'KIDNAPPING & ABDUCTION_TOTAL',
       'KIDNAPPING & ABDUCTION', 'KIDNAPPING & ABDUCTION IN ORDER TO MURDER',
       'KIDNAPPING FOR RANSOM',
       'KIDNAPPING & ABDUCTION OF WOMEN TO COMPEL HER FOR MARRIAGE',
       'OTHER KIDNAPPING', 'DACOITY', 'DACOITY WITH MURDER', 'OTHER DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'CRIMINAL TRESPASS OR BURGLARY',
       'HOUSE TRESPASS & HOUSE BREAKING', 'THEFT', 'AUTO THEFT',
       'OTHER THEFTS', 'UNLAWFUL ASSEMBLY', 'RIOTS', 'RIOTS_COMMUNAL',
       'RIOTS_INDUSTRIAL', 'RIOTS_POLITICAL', 'RIOTS_CASTE CONFLICT',
       'RIOTS_SC/STS VS NON-SCS/STS', 'RIOTS_OTHER CASTE CONFLICT',
       'RIOTS_AGRARIAN', 'RIOTS_STUDENTS', 'RIOTS_SECTARIAN', 'RIOTS_OTHERS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'FORGERY', 'COUNTERFEITING',
       'COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN',
       'COUNTERFEITING GOVERNMENT STAMP', 'COUNTERFEIT CURRENCY & BANK NOTES',
       'COUNTERFEITING CURRENCY NOTES/BANK NOTES',
       'USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES',
       'MAKING OR USING DOCUMENTS RESEMBLING CURRENCY', 'ARSON',
       'GRIEVOUS HURT', 'HURT', 'ACID ATTACK', 'ATTEMPT TO ACID ATTACK',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [419]:
df1=df.append(dw14,ignore_index=True)

In [420]:
df1

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,OTHER OFFENCES AGAINST STATE,OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS,PROMOTING ENMITY BETWEEN DIFFERENT GROUPS,"IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION",EXTORTION,DISCLOSURE OF IDENTITY OF VICTIMS,INCIDENCE OF RASH DRIVING,HUMANTRAFFICKING,UNNATURAL OFFENCE,TOTAL COGNIZABLE IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60.0,17,50,0,50.0,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125.0,1,23,0,23.0,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ANDHRA PRADESH,CHITTOOR,2001,101,57.0,2,27,0,27.0,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53.0,1,20,0,20.0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67.0,1,23,0,23.0,49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10673,NaN,Lakshadweep,2014,0,NaN,0,1,0,NaN,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,81.0
10674,NaN,Total,2014,0,NaN,0,1,0,NaN,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,81.0
10675,NaN,Karaikal,2014,6,NaN,0,3,0,NaN,1,...,0.0,2.0,2.0,0.0,0.0,1.0,199.0,0.0,0.0,671.0
10676,NaN,Puducherry,2014,19,NaN,3,7,1,NaN,7,...,0.0,2.0,2.0,0.0,9.0,0.0,974.0,0.0,0.0,2913.0
10677,NaN,Total,2014,25,NaN,3,10,1,NaN,8,...,0.0,4.0,4.0,0.0,9.0,1.0,1173.0,0.0,0.0,3584.0

In [544]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [545]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',
       'ATTEMPT TO COMMIT CULPABLE HOMICIDE', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE', 'RAPE_OTHERS',
       'ATTEMPT TO COMMIT RAPE', 'KIDNAPPING & ABDUCTION_TOTAL',
       'KIDNAPPING & ABDUCTION', 'KIDNAPPING & ABDUCTION IN ORDER TO MURDER',
       'KIDNAPPING FOR RANSOM',
       'KIDNAPPING & ABDUCTION OF WOMEN TO COMPEL HER FOR MARRIAGE',
       'OTHER KIDNAPPING', 'DACOITY', 'DACOITY WITH MURDER', 'OTHER DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'CRIMINAL TRESPASS OR BURGLARY',
       'HOUSE TRESPASS & HOUSE BREAKING', 'THEFT', 'AUTO THEFT',
       'OTHER THEFTS', 'UNLAWFUL ASSEMBLY', 'RIOTS', 'RIOTS_COMMUNAL',
       'RIOTS_INDUSTRIAL', 'RIOTS_POLITICAL', 'RIOTS_CASTE CONFLICT',
       'RIOTS_SC/STS VS NON-SCS/STS', 'RIOTS_OTHER CASTE CONFLICT',
       'RIOTS_AGRARIAN', 'RIOTS_STUDENTS', 'RIOTS_SECTARIAN', 'RIOTS_OTHERS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'FORGERY', 'COUNTERFEITING',
       'COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN',
       'COUNTERFEITING GOVERNMENT STAMP', 'COUNTERFEIT CURRENCY & BANK NOTES',
       'COUNTERFEITING CURRENCY NOTES/BANK NOTES',
       'USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES',
       'MAKING OR USING DOCUMENTS RESEMBLING CURRENCY', 'ARSON',
       'GRIEVOUS HURT', 'HURT', 'ACID ATTACK', 'ATTEMPT TO ACID ATTACK',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [546]:
dw14["CULPABLE HOMICIDE NOT AMOUNTING TO MURDER"]=dw14["CULPABLE HOMICIDE NOT AMOUNTING TO MURDER"]+dw14["ATTEMPT TO COMMIT CULPABLE HOMICIDE"]

In [548]:
dw14.drop("ATTEMPT TO COMMIT CULPABLE HOMICIDE", inplace=True, axis=1)

In [549]:
dw14

,STATES/UTS,DISTRICT,YEAR,MURDER,ATTEMPT TO COMMIT MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,CUSTODIAL_GANG RAPE,CUSTODIAL_OTHER RAPE,...,OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS,PROMOTING ENMITY BETWEEN DIFFERENT GROUPS,"IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION",EXTORTION,DISCLOSURE OF IDENTITY OF VICTIMS,INCIDENCE OF RASH DRIVING,HUMANTRAFFICKING,UNNATURAL OFFENCE,OTHER IPC CRIMES,TOTAL COGNIZABLE IPC CRIMES
0,Andhra Pradesh,Anantapur,2014,134,171,8,35,0,0,0,...,0,0,0,0,0,1038,0,0,3800,8376
1,Andhra Pradesh,Chittoor,2014,84,170,2,32,0,0,0,...,0,0,0,19,0,249,0,0,2567,5374
2,Andhra Pradesh,Cuddapah,2014,80,162,1,28,0,0,0,...,0,0,0,0,0,948,0,0,2604,5803
3,Andhra Pradesh,East Godavari,2014,64,84,2,85,0,0,0,...,0,0,0,32,0,39,0,0,3791,7630
4,Andhra Pradesh,Guntakal Railway,2014,14,4,0,0,0,0,0,...,0,0,0,0,0,1,0,0,37,490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,Lakshadweep,Lakshadweep,2014,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,30,81
834,Lakshadweep,Total,2014,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,30,81
835,Puducherry,Karaikal,2014,6,1,0,3,0,0,0,...,2,2,0,0,1,199,0,0,322,671
836,Puducherry,Puducherry,2014,19,14,3,7,1,0,1,...,2,2,0,9,0,974,0,0,1014,2913
837,Puducherry,Total,2014,25,15,3,10,1,0,1,...,4,4,0,9,1,1173,0,0,1336,3584

In [550]:
dw14['RAPE']=dw14['RAPE']+dw14['CUSTODIAL RAPE']+dw14['CUSTODIAL_GANG RAPE']+dw14['CUSTODIAL_OTHER RAPE']+dw14['RAPE OTHER THAN CUSTODIAL']+dw14['RAPE_GANG RAPE']+dw14['RAPE_OTHERS']

In [551]:
dw14.drop("RAPE_OTHERS",inplace=True, axis=1)

In [552]:
dw14

,STATES/UTS,DISTRICT,YEAR,MURDER,ATTEMPT TO COMMIT MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,CUSTODIAL_GANG RAPE,CUSTODIAL_OTHER RAPE,...,OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS,PROMOTING ENMITY BETWEEN DIFFERENT GROUPS,"IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION",EXTORTION,DISCLOSURE OF IDENTITY OF VICTIMS,INCIDENCE OF RASH DRIVING,HUMANTRAFFICKING,UNNATURAL OFFENCE,OTHER IPC CRIMES,TOTAL COGNIZABLE IPC CRIMES
0,Andhra Pradesh,Anantapur,2014,134,171,8,105,0,0,0,...,0,0,0,0,0,1038,0,0,3800,8376
1,Andhra Pradesh,Chittoor,2014,84,170,2,96,0,0,0,...,0,0,0,19,0,249,0,0,2567,5374
2,Andhra Pradesh,Cuddapah,2014,80,162,1,84,0,0,0,...,0,0,0,0,0,948,0,0,2604,5803
3,Andhra Pradesh,East Godavari,2014,64,84,2,255,0,0,0,...,0,0,0,32,0,39,0,0,3791,7630
4,Andhra Pradesh,Guntakal Railway,2014,14,4,0,0,0,0,0,...,0,0,0,0,0,1,0,0,37,490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,Lakshadweep,Lakshadweep,2014,0,0,0,3,0,0,0,...,0,0,0,0,0,1,0,0,30,81
834,Lakshadweep,Total,2014,0,0,0,3,0,0,0,...,0,0,0,0,0,1,0,0,30,81
835,Puducherry,Karaikal,2014,6,1,0,9,0,0,0,...,2,2,0,0,1,199,0,0,322,671
836,Puducherry,Puducherry,2014,19,14,3,21,1,0,1,...,2,2,0,9,0,974,0,0,1014,2913
837,Puducherry,Total,2014,25,15,3,30,1,0,1,...,4,4,0,9,1,1173,0,0,1336,3584

In [553]:
dw14["RAPE"]=dw14["RAPE"]+dw14["ATTEMPT TO COMMIT RAPE"]

In [554]:
dw14.drop("ATTEMPT TO COMMIT RAPE",inplace=True,axis=1)

In [432]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE',
       'KIDNAPPING & ABDUCTION_TOTAL', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING & ABDUCTION IN ORDER TO MURDER', 'KIDNAPPING FOR RANSOM',
       'KIDNAPPING & ABDUCTION OF WOMEN TO COMPEL HER FOR MARRIAGE',
       'OTHER KIDNAPPING', 'DACOITY', 'DACOITY WITH MURDER', 'OTHER DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'CRIMINAL TRESPASS OR BURGLARY',
       'HOUSE TRESPASS & HOUSE BREAKING', 'THEFT', 'AUTO THEFT',
       'OTHER THEFTS', 'UNLAWFUL ASSEMBLY', 'RIOTS', 'RIOTS_COMMUNAL',
       'RIOTS_INDUSTRIAL', 'RIOTS_POLITICAL', 'RIOTS_CASTE CONFLICT',
       'RIOTS_SC/STS VS NON-SCS/STS', 'RIOTS_OTHER CASTE CONFLICT',
       'RIOTS_AGRARIAN', 'RIOTS_STUDENTS', 'RIOTS_SECTARIAN', 'RIOTS_OTHERS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'FORGERY', 'COUNTERFEITING',
       'COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN',
       'COUNTERFEITING GOVERNMENT STAMP', 'COUNTERFEIT CURRENCY & BANK NOTES',
       'COUNTERFEITING CURRENCY NOTES/BANK NOTES',
       'USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES',
       'MAKING OR USING DOCUMENTS RESEMBLING CURRENCY', 'ARSON',
       'GRIEVOUS HURT', 'HURT', 'ACID ATTACK', 'ATTEMPT TO ACID ATTACK',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [555]:
dw14["KIDNAPPING & ABDUCTION_TOTAL"]=dw14['KIDNAPPING & ABDUCTION_TOTAL']+dw14['KIDNAPPING & ABDUCTION']+dw14['KIDNAPPING & ABDUCTION IN ORDER TO MURDER']+dw14['KIDNAPPING FOR RANSOM']+dw14['KIDNAPPING & ABDUCTION OF WOMEN TO COMPEL HER FOR MARRIAGE']+dw14['OTHER KIDNAPPING']

In [556]:
dw14.drop('KIDNAPPING & ABDUCTION',inplace=True,axis=1)
dw14.drop('KIDNAPPING & ABDUCTION IN ORDER TO MURDER',inplace=True,axis=1)
dw14.drop('KIDNAPPING FOR RANSOM',inplace=True,axis=1)
dw14.drop('KIDNAPPING & ABDUCTION OF WOMEN TO COMPEL HER FOR MARRIAGE',inplace=True,axis=1)
dw14.drop('OTHER KIDNAPPING',inplace=True,axis=1)

In [557]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE',
       'KIDNAPPING & ABDUCTION_TOTAL', 'DACOITY', 'DACOITY WITH MURDER',
       'OTHER DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'CRIMINAL TRESPASS OR BURGLARY',
       'HOUSE TRESPASS & HOUSE BREAKING', 'THEFT', 'AUTO THEFT',
       'OTHER THEFTS', 'UNLAWFUL ASSEMBLY', 'RIOTS', 'RIOTS_COMMUNAL',
       'RIOTS_INDUSTRIAL', 'RIOTS_POLITICAL', 'RIOTS_CASTE CONFLICT',
       'RIOTS_SC/STS VS NON-SCS/STS', 'RIOTS_OTHER CASTE CONFLICT',
       'RIOTS_AGRARIAN', 'RIOTS_STUDENTS', 'RIOTS_SECTARIAN', 'RIOTS_OTHERS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'FORGERY', 'COUNTERFEITING',
       'COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN',
       'COUNTERFEITING GOVERNMENT STAMP', 'COUNTERFEIT CURRENCY & BANK NOTES',
       'COUNTERFEITING CURRENCY NOTES/BANK NOTES',
       'USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES',
       'MAKING OR USING DOCUMENTS RESEMBLING CURRENCY', 'ARSON',
       'GRIEVOUS HURT', 'HURT', 'ACID ATTACK', 'ATTEMPT TO ACID ATTACK',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [558]:
dw14["DACOITY"]=dw14['DACOITY']+dw14['DACOITY WITH MURDER']+dw14['OTHER DACOITY']

In [559]:
dw14.drop("DACOITY WITH MURDER",inplace=True,axis=1)
dw14.drop("OTHER DACOITY",inplace=True,axis=1)

In [560]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE',
       'KIDNAPPING & ABDUCTION_TOTAL', 'DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'CRIMINAL TRESPASS OR BURGLARY',
       'HOUSE TRESPASS & HOUSE BREAKING', 'THEFT', 'AUTO THEFT',
       'OTHER THEFTS', 'UNLAWFUL ASSEMBLY', 'RIOTS', 'RIOTS_COMMUNAL',
       'RIOTS_INDUSTRIAL', 'RIOTS_POLITICAL', 'RIOTS_CASTE CONFLICT',
       'RIOTS_SC/STS VS NON-SCS/STS', 'RIOTS_OTHER CASTE CONFLICT',
       'RIOTS_AGRARIAN', 'RIOTS_STUDENTS', 'RIOTS_SECTARIAN', 'RIOTS_OTHERS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'FORGERY', 'COUNTERFEITING',
       'COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN',
       'COUNTERFEITING GOVERNMENT STAMP', 'COUNTERFEIT CURRENCY & BANK NOTES',
       'COUNTERFEITING CURRENCY NOTES/BANK NOTES',
       'USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES',
       'MAKING OR USING DOCUMENTS RESEMBLING CURRENCY', 'ARSON',
       'GRIEVOUS HURT', 'HURT', 'ACID ATTACK', 'ATTEMPT TO ACID ATTACK',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [561]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [562]:
dw14['CRIMINAL TRESPASS/BURGLARY']=dw14['CRIMINAL TRESPASS/BURGLARY']+ dw14['CRIMINAL TRESPASS OR BURGLARY']+dw14['HOUSE TRESPASS & HOUSE BREAKING']

In [563]:
dw14.drop('CRIMINAL TRESPASS OR BURGLARY',inplace=True,axis=1)
dw14.drop('HOUSE TRESPASS & HOUSE BREAKING',inplace=True,axis=1)

In [564]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE',
       'KIDNAPPING & ABDUCTION_TOTAL', 'DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFTS',
       'UNLAWFUL ASSEMBLY', 'RIOTS', 'RIOTS_COMMUNAL', 'RIOTS_INDUSTRIAL',
       'RIOTS_POLITICAL', 'RIOTS_CASTE CONFLICT',
       'RIOTS_SC/STS VS NON-SCS/STS', 'RIOTS_OTHER CASTE CONFLICT',
       'RIOTS_AGRARIAN', 'RIOTS_STUDENTS', 'RIOTS_SECTARIAN', 'RIOTS_OTHERS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'FORGERY', 'COUNTERFEITING',
       'COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN',
       'COUNTERFEITING GOVERNMENT STAMP', 'COUNTERFEIT CURRENCY & BANK NOTES',
       'COUNTERFEITING CURRENCY NOTES/BANK NOTES',
       'USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES',
       'MAKING OR USING DOCUMENTS RESEMBLING CURRENCY', 'ARSON',
       'GRIEVOUS HURT', 'HURT', 'ACID ATTACK', 'ATTEMPT TO ACID ATTACK',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [565]:
dw14['RIOTS']=dw14['RIOTS']+dw14['RIOTS_COMMUNAL']+dw14['RIOTS_INDUSTRIAL']+dw14['RIOTS_POLITICAL']+dw14['RIOTS_CASTE CONFLICT']+dw14['RIOTS_SC/STS VS NON-SCS/STS']+dw14['RIOTS_OTHER CASTE CONFLICT']+dw14['RIOTS_AGRARIAN']+dw14['RIOTS_STUDENTS']+dw14['RIOTS_SECTARIAN']+dw14['RIOTS_OTHERS']

In [566]:
dw14.drop('RIOTS_COMMUNAL',inplace=True,axis=1)
dw14.drop('RIOTS_INDUSTRIAL',inplace=True,axis=1)
dw14.drop('RIOTS_POLITICAL',inplace=True,axis=1)
dw14.drop('RIOTS_CASTE CONFLICT',inplace=True, axis=1)
dw14.drop('RIOTS_SC/STS VS NON-SCS/STS',inplace=True, axis=1)
dw14.drop('RIOTS_OTHER CASTE CONFLICT',inplace=True, axis=1)
dw14.drop('RIOTS_AGRARIAN',inplace=True,axis=1)
dw14.drop('RIOTS_STUDENTS',inplace=True,axis=1)
dw14.drop('RIOTS_SECTARIAN',inplace=True,axis=1)
dw14.drop('RIOTS_OTHERS',inplace=True,axis=1)

In [567]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE',
       'KIDNAPPING & ABDUCTION_TOTAL', 'DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFTS',
       'UNLAWFUL ASSEMBLY', 'RIOTS', 'CRIMINAL BREACH OF TRUST', 'CHEATING',
       'FORGERY', 'COUNTERFEITING',
       'COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN',
       'COUNTERFEITING GOVERNMENT STAMP', 'COUNTERFEIT CURRENCY & BANK NOTES',
       'COUNTERFEITING CURRENCY NOTES/BANK NOTES',
       'USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',
       'MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES',
       'MAKING OR USING DOCUMENTS RESEMBLING CURRENCY', 'ARSON',
       'GRIEVOUS HURT', 'HURT', 'ACID ATTACK', 'ATTEMPT TO ACID ATTACK',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [568]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [569]:
dw14['COUNTERFEITING']=dw14['COUNTERFEITING']+dw14['COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN']+dw14['COUNTERFEITING GOVERNMENT STAMP']+dw14['COUNTERFEIT CURRENCY & BANK NOTES']+dw14['COUNTERFEITING CURRENCY NOTES/BANK NOTES']+dw14['USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES']+dw14['POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES']+dw14['MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES']+dw14['MAKING OR USING DOCUMENTS RESEMBLING CURRENCY']

In [570]:
dw14.drop('COUNTERFEIT OFFENCES RELATED TO COUNTERFEIT COIN',inplace=True,axis=1)
dw14.drop('COUNTERFEITING GOVERNMENT STAMP',inplace=True,axis=1)
dw14.drop('COUNTERFEIT CURRENCY & BANK NOTES',inplace=True,axis=1)
dw14.drop('COUNTERFEITING CURRENCY NOTES/BANK NOTES',inplace=True,axis=1)
dw14.drop('USING FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',inplace=True,axis=1)
dw14.drop('POSSESSION OF FORGED OR COUNTERFEITING CURRENCY/BANK NOTES',inplace=True,axis=1)
dw14.drop('MAKING OR POSSESSING MATERIALS FOR FORGED CURRENCY/BANK NOTES',inplace=True,axis=1)
dw14.drop('MAKING OR USING DOCUMENTS RESEMBLING CURRENCY',inplace=True,axis=1)

In [571]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE',
       'KIDNAPPING & ABDUCTION_TOTAL', 'DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFTS',
       'UNLAWFUL ASSEMBLY', 'RIOTS', 'CRIMINAL BREACH OF TRUST', 'CHEATING',
       'FORGERY', 'COUNTERFEITING', 'ARSON', 'GRIEVOUS HURT', 'HURT',
       'ACID ATTACK', 'ATTEMPT TO ACID ATTACK', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [572]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [573]:
dw14['GRIEVOUS HURT']=dw14['GRIEVOUS HURT']+dw14['HURT']+dw14['ACID ATTACK']+dw14['ATTEMPT TO ACID ATTACK']

In [574]:
dw14.drop("HURT",inplace=True,axis=1)
dw14.drop("ACID ATTACK",inplace=True,axis=1)
dw14.drop("ATTEMPT TO ACID ATTACK",inplace=True,axis=1)

In [575]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE',
       'KIDNAPPING & ABDUCTION_TOTAL', 'DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFTS',
       'UNLAWFUL ASSEMBLY', 'RIOTS', 'CRIMINAL BREACH OF TRUST', 'CHEATING',
       'FORGERY', 'COUNTERFEITING', 'ARSON', 'GRIEVOUS HURT', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'SEXUAL HARASSMENT',
       'ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',
       'VOYEURISM', 'STALKING', 'OTHER ASSAULT ON WOMEN',
       'INSULT TO THE MODESTY OF WOMEN', 'AT OFFICE PREMISES',
       'OTHER PLACES RELATED TO WORK', 'IN PUBLIC TRANSPORT SYSTEM',
       'PLACES OTHER THAN 231, 232 & 233',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [576]:
dw14['ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY']=dw14['ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY']+dw14['SEXUAL HARASSMENT']+dw14['ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE']+dw14['VOYEURISM']+dw14['STALKING']+dw14['OTHER ASSAULT ON WOMEN']+dw14['INSULT TO THE MODESTY OF WOMEN']+dw14['AT OFFICE PREMISES']+dw14['OTHER PLACES RELATED TO WORK']+dw14['IN PUBLIC TRANSPORT SYSTEM']+dw14['PLACES OTHER THAN 231, 232 & 233']

In [577]:
dw14.drop("SEXUAL HARASSMENT",inplace=True,axis=1)
dw14.drop('ASSAULT OR USE OF CRIMINAL FORCE TO WOMEN WITH INTENT TO DISROBE',inplace=True,axis=1)
dw14.drop('VOYEURISM',inplace=True,axis=1)
dw14.drop("STALKING",inplace=True,axis=1)
dw14.drop('OTHER ASSAULT ON WOMEN',inplace=True,axis=1)
dw14.drop('INSULT TO THE MODESTY OF WOMEN',inplace=True,axis=1)
dw14.drop('AT OFFICE PREMISES',inplace=True,axis=1)
dw14.drop('OTHER PLACES RELATED TO WORK',inplace=True,axis=1)
dw14.drop('IN PUBLIC TRANSPORT SYSTEM',inplace=True,axis=1)
dw14.drop('PLACES OTHER THAN 231, 232 & 233',inplace=True,axis=1)

In [578]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'CUSTODIAL_OTHER RAPE',
       'RAPE OTHER THAN CUSTODIAL', 'RAPE_GANG RAPE',
       'KIDNAPPING & ABDUCTION_TOTAL', 'DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFTS',
       'UNLAWFUL ASSEMBLY', 'RIOTS', 'CRIMINAL BREACH OF TRUST', 'CHEATING',
       'FORGERY', 'COUNTERFEITING', 'ARSON', 'GRIEVOUS HURT', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'DEATHS DUE TO NEGLIGENT DRIVING/ACT',
       'DEATHS DUE TO OTHER CAUSES', 'OFFENCES AGAINST STATE', 'SEDITION',
       'OTHER OFFENCES AGAINST STATE',
       'OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',
       'IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',
       'EXTORTION', 'DISCLOSURE OF IDENTITY OF VICTIMS',
       'INCIDENCE OF RASH DRIVING', 'HUMANTRAFFICKING', 'UNNATURAL OFFENCE',
       'OTHER IPC CRIMES', 'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [579]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [580]:
dw14['CAUSING DEATH BY NEGLIGENCE']=dw14['CAUSING DEATH BY NEGLIGENCE']+dw14['DEATHS DUE TO NEGLIGENT DRIVING/ACT']+dw14['DEATHS DUE TO OTHER CAUSES']+dw14['OFFENCES AGAINST STATE']+dw14['SEDITION']+dw14['OTHER OFFENCES AGAINST STATE']+dw14['OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS']+dw14['PROMOTING ENMITY BETWEEN DIFFERENT GROUPS']+dw14['IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION']+dw14['EXTORTION']+dw14['DISCLOSURE OF IDENTITY OF VICTIMS']+dw14['INCIDENCE OF RASH DRIVING']+dw14['HUMANTRAFFICKING']+dw14['UNNATURAL OFFENCE']

In [581]:
dw14.drop('DEATHS DUE TO NEGLIGENT DRIVING/ACT',inplace=True,axis=1)
dw14.drop('DEATHS DUE TO OTHER CAUSES',inplace=True,axis=1)

In [582]:
dw14.drop('OFFENCES AGAINST STATE',inplace=True,axis=1)
dw14.drop('SEDITION',inplace=True,axis=1)
dw14.drop('OTHER OFFENCES AGAINST STATE',inplace=True,axis=1)
dw14.drop('OFFENCES PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',inplace=True,axis=1)
dw14.drop('PROMOTING ENMITY BETWEEN DIFFERENT GROUPS',inplace=True,axis=1)
dw14.drop('IMPUTATION, ASSERTIONS PREJUDICIAL TO NATIONAL INTEGRATION',inplace=True,axis=1)
dw14.drop('EXTORTION',inplace=True,axis=1)
dw14.drop('DISCLOSURE OF IDENTITY OF VICTIMS',inplace=True,axis=1)
dw14.drop('INCIDENCE OF RASH DRIVING',inplace=True,axis=1)
dw14.drop('HUMANTRAFFICKING',inplace=True,axis=1)
dw14.drop('UNNATURAL OFFENCE',inplace=True,axis=1)

In [585]:
dw14.drop("UNLAWFUL ASSEMBLY",inplace=True,axis=1)

In [586]:
dw14['CUSTODIAL_GANG RAPE']=dw14['CUSTODIAL_GANG RAPE']+dw14['CUSTODIAL_OTHER RAPE']+dw14['RAPE OTHER THAN CUSTODIAL']+dw14['RAPE_GANG RAPE']

In [587]:
dw14.drop("CUSTODIAL_OTHER RAPE",inplace=True,axis=1)
dw14.drop('RAPE OTHER THAN CUSTODIAL',inplace=True,axis=1)
dw14.drop('RAPE_GANG RAPE',inplace=True,axis=1)

In [588]:
df['KIDNAPPING & ABDUCTION']=df['KIDNAPPING & ABDUCTION']+df['KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS']+df['KIDNAPPING AND ABDUCTION OF OTHERS']

In [589]:
df.drop('KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',inplace=True,axis=1)
df.drop('KIDNAPPING AND ABDUCTION OF OTHERS',inplace=True,axis=1)

In [591]:
df.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [592]:
dw14.columns

Index(['STATES/UTS', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO COMMIT MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'CUSTODIAL_GANG RAPE', 'KIDNAPPING & ABDUCTION_TOTAL', 'DACOITY',
       'MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY', 'ROBBERY',
       'CRIMINAL TRESPASS/BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFTS',
       'RIOTS', 'CRIMINAL BREACH OF TRUST', 'CHEATING', 'FORGERY',
       'COUNTERFEITING', 'ARSON', 'GRIEVOUS HURT', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES',
       'TOTAL COGNIZABLE IPC CRIMES'],
      dtype='object')

In [598]:
dw14.rename(columns = {'STATES/UTS':'STATE/UT', 'ATTEMPT TO COMMIT MURDER':'ATTEMPT TO MURDER','CUSTODIAL_GANG RAPE':'OTHER RAPE','KIDNAPPING & ABDUCTION_TOTAL':'KIDNAPPING & ABDUCTION','MAKING PREPARATION AND ASSEMBLY FOR COMMITTING DACOITY':'PREPARATION AND ASSEMBLY FOR DACOITY','CRIMINAL TRESPASS/BURGLARY':'BURGLARY','GRIEVOUS HURT':'HURT/GREVIOUS HURT','TOTAL COGNIZABLE IPC CRIMES':'TOTAL IPC CRIMES'}, inplace = True)

dw14.columns

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFTS', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'FORGERY', 'COUNTERFEITING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [733]:
df

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,92,...,30,1131,16,149,34,175,0,181,1518,4154
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,106,...,69,1543,7,118,24,154,0,270,754,4125
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,118,...,38,2088,14,112,83,186,0,404,1262,5818
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,50,...,23,795,17,126,38,57,0,233,1181,3140
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,98,...,41,1244,12,109,58,247,0,431,2313,6507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,Lakshadweep,LAKSHADWEEP,2013,0,0,0,2,0,2,0,...,1,5,0,1,0,0,0,0,18,40
9836,Lakshadweep,ZZ TOTAL,2013,0,0,0,2,0,2,0,...,1,5,0,1,0,0,0,0,18,40
9837,Puducherry,KARAIKAL,2013,6,3,0,6,0,6,6,...,3,160,1,1,1,1,0,32,329,643
9838,Puducherry,PUDUCHERRY,2013,25,8,2,11,0,11,76,...,13,555,0,11,7,7,0,206,1464,3113
9839,Puducherry,ZZ TOTAL,2013,31,11,2,17,0,17,82,...,16,715,1,12,8,8,0,238,1793,3756

In [651]:
dfF=pd.concat([df,dw14],axis=0,ignore_index=True)

In [652]:
dfF

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,OTHER THEFTS,FORGERY,COUNTERFEITING,IMPORTATION OF GIRLS FROM FOREIGN COUNTRY
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,92,...,34.0,175,0.0,181,1518,4154,NaN,NaN,NaN,NaN
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,106,...,24.0,154,0.0,270,754,4125,NaN,NaN,NaN,NaN
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,118,...,83.0,186,0.0,404,1262,5818,NaN,NaN,NaN,NaN
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,50,...,38.0,57,0.0,233,1181,3140,NaN,NaN,NaN,NaN
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,98,...,58.0,247,0.0,431,2313,6507,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10673,Lakshadweep,Lakshadweep,2014,0,0,0,3,0,1,0,...,NaN,0,NaN,1,30,81,15.0,2.0,0.0,0.0
10674,Lakshadweep,Total,2014,0,0,0,3,0,1,0,...,NaN,0,NaN,1,30,81,15.0,2.0,0.0,0.0
10675,Puducherry,Karaikal,2014,6,1,0,9,0,3,2,...,NaN,1,NaN,292,322,671,22.0,5.0,0.0,0.0
10676,Puducherry,Puducherry,2014,19,14,3,21,1,8,24,...,NaN,3,NaN,1317,1014,2913,117.0,8.0,0.0,0.0
10677,Puducherry,Total,2014,25,15,3,30,1,11,26,...,NaN,4,NaN,1609,1336,3584,139.0,13.0,0.0,0.0

In [653]:
dfF=dfF.fillna(0)

In [654]:
dfF["STATE/UT"]=dfF["STATE/UT"].str.upper()

In [284]:
dfF.to_csv("processedData.csv",index=False)

In [655]:
dfF["DISTRICT"]=dfF["DISTRICT"].str.upper()

In [656]:
dfF

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,OTHER THEFTS,FORGERY,COUNTERFEITING,IMPORTATION OF GIRLS FROM FOREIGN COUNTRY
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,92,...,34.0,175,0.0,181,1518,4154,0.0,0.0,0.0,0.0
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,106,...,24.0,154,0.0,270,754,4125,0.0,0.0,0.0,0.0
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,118,...,83.0,186,0.0,404,1262,5818,0.0,0.0,0.0,0.0
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,50,...,38.0,57,0.0,233,1181,3140,0.0,0.0,0.0,0.0
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,98,...,58.0,247,0.0,431,2313,6507,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10673,LAKSHADWEEP,LAKSHADWEEP,2014,0,0,0,3,0,1,0,...,0.0,0,0.0,1,30,81,15.0,2.0,0.0,0.0
10674,LAKSHADWEEP,TOTAL,2014,0,0,0,3,0,1,0,...,0.0,0,0.0,1,30,81,15.0,2.0,0.0,0.0
10675,PUDUCHERRY,KARAIKAL,2014,6,1,0,9,0,3,2,...,0.0,1,0.0,292,322,671,22.0,5.0,0.0,0.0
10676,PUDUCHERRY,PUDUCHERRY,2014,19,14,3,21,1,8,24,...,0.0,3,0.0,1317,1014,2913,117.0,8.0,0.0,0.0
10677,PUDUCHERRY,TOTAL,2014,25,15,3,30,1,11,26,...,0.0,4,0.0,1609,1336,3584,139.0,13.0,0.0,0.0

#<h1>Processing the next set of data</h1>

In [481]:
pc1to12

,STATE/UT,YEAR,RESIDENTIAL PREMISES - Dacoity,RESIDENTIAL PREMISES - Robbery,RESIDENTIAL PREMISES - Burglary,RESIDENTIAL PREMISES - Theft,HIGHWAYS - Dacoity,HIGHWAYS - Robbery,HIGHWAYS - Burglary,HIGHWAYS - Theft,...,COMMERCIAL ESTABLISHMENTS - Burglary,COMMERCIAL ESTABLISHMENTS - Theft,OTHER PLACES - Dacoity,OTHER PLACES - Robbery,OTHER PLACES - Burglary,OTHER PLACES - Theft,TOTAL - Dacoity,TOTAL - Robbery,TOTAL - Burglary,TOTAL - Theft
0,ANDHRA PRADESH,2001,100,177,5158,4257,57,172,31,74,...,1041,2502,37,232,862,8849,214,629,7220,16751
1,ARUNACHAL PRADESH,2001,9,26,99,131,0,0,0,8,...,84,54,8,40,65,249,22,84,248,443
2,ASSAM,2001,381,191,1695,2901,46,136,7,87,...,442,967,77,261,271,1342,532,687,2423,5367
3,BIHAR,2001,818,326,2486,4741,162,826,0,257,...,231,686,210,880,505,2582,1291,2203,3233,9701
4,CHHATTISGARH,2001,54,42,3336,1417,10,38,12,72,...,370,299,15,239,420,2835,87,338,4144,4812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,DELHI,2012,10,101,1249,7076,1,32,0,189,...,285,1370,17,431,178,12749,28,608,1715,22032
452,LAKSHADWEEP,2012,0,0,3,7,0,0,0,0,...,0,0,0,0,0,0,0,0,3,7
453,PUDUCHERRY,2012,1,4,47,42,0,0,0,0,...,26,20,2,8,4,596,5,16,77,658
454,TOTAL (UTs),2012,11,123,1515,7974,1,32,0,199,...,412,2042,28,468,217,13554,44,694,2149,24440
455,TOTAL (ALL-INDIA),2012,1288,2821,60698,81861,838,5000,316,27802,...,12228,29661,1797,17480,19154,181277,4314,27343,92892,337407

In [482]:
dfPc=pd.concat([pc1to12,pc13],ignore_index=True)

In [483]:
dfPc["STATE/UT"]=dfPc["STATE/UT"].str.upper()

In [484]:
dfPc["STATE/UT"]

0         ANDHRA PRADESH
1      ARUNACHAL PRADESH
2                  ASSAM
3                  BIHAR
4           CHHATTISGARH
             ...
489             DELHI UT
490          LAKSHADWEEP
491           PUDUCHERRY
492          TOTAL (UTS)
493    TOTAL (ALL-INDIA)
Name: STATE/UT, Length: 494, dtype: object

In [485]:
dfPc.columns

Index(['STATE/UT', 'YEAR', 'RESIDENTIAL PREMISES - Dacoity',
       'RESIDENTIAL PREMISES - Robbery', 'RESIDENTIAL PREMISES - Burglary',
       'RESIDENTIAL PREMISES - Theft', 'HIGHWAYS - Dacoity',
       'HIGHWAYS - Robbery', 'HIGHWAYS - Burglary', 'HIGHWAYS - Theft',
       'RIVER and SEA - Dacoity', 'RIVER and SEA - Robbery',
       'RIVER and SEA - Burglary', 'RIVER and SEA - Theft',
       'RAILWAYS - Dacoity', 'RAILWAYS - Robbery', 'RAILWAYS - Burglary',
       'RAILWAYS - Theft', 'BANKS - Dacoity', 'BANKS - Robbery',
       'BANKS - Burglary', 'BANKS - Theft',
       'COMMERCIAL ESTABLISHMENTS - Dacoity',
       'COMMERCIAL ESTABLISHMENTS - Robbery',
       'COMMERCIAL ESTABLISHMENTS - Burglary',
       'COMMERCIAL ESTABLISHMENTS - Theft', 'OTHER PLACES - Dacoity',
       'OTHER PLACES - Robbery', 'OTHER PLACES - Burglary',
       'OTHER PLACES - Theft', 'TOTAL - Dacoity', 'TOTAL - Robbery',
       'TOTAL - Burglary', 'TOTAL - Theft'],
      dtype='object')

In [486]:
pc14.columns

Index(['States/UTs', 'Year', 'Residence_Dacoity_Cases reported',
       'Residence_Dacoity_Value of property stolen',
       'Residence_Robbery_Cases reported',
       'Residence_Robbery_Value of property stolen',
       'Residence_Burglary_Cases reported',
       'Residence_Burglary_Value of property stolen',
       'Residence_Theft_Cases reported',
       'Residence_Theft_Value of property stolen',
       'Highways_Dacoity_Cases reported',
       'Highways_Dacoity_Value of property stolen',
       'Highways_Robbery_Cases reported',
       'Highways_Robbery_Value of property stolen',
       'Highways_Burglary_Cases reported',
       'Highways_Burglary_Value of property stolen',
       'Highways_Theft_Cases reported',
       'Highways_Theft_Value of property stolen',
       'RiverOrSea_Dacoity_Cases reported',
       'RiverOrSea_Dacoity_Value of property stolen',
       'RiverOrSea_Robbery_Cases reported',
       'RiverOrSea_Robbery_Value of property stolen',
       'RiverOrSea_Burglary_Cases reported',
       'RiverOrSea_Burglary_Value of property stolen',
       'RiverOrSea_Theft_Cases reported',
       'RiverOrSea_Theft_Value of property stolen',
       'Railways_Dacoity_Cases reported',
       'Railways_Dacoity_Value of property stolen',
       'Railways_Robbery_Cases reported',
       'Railways_Robbery_Value of property stolen',
       'Railways_Burglary_Cases reported',
       'Railways_Burglary_Value of property stolen',
       'Railways_Theft_Cases reported',
       'Railways_Theft_Value of property stolen',
       'Religious Places_Dacoity_Cases reported',
       'Religious Places_Dacoity_Value of property stolen',
       'Religious Places_Robbery_Cases reported',
       'Religious Places_Robbery_Value of property stolen',
       'Religious Places_Burglary_Cases reported',
       'Religious Places_Burglary_Value of property stolen',
       'Religious Places_Theft_Cases reported',
       'Religious Places_Theft_Value of property stolen',
       'ATM_Dacoity_Cases reported', 'ATM_Dacoity_Value of property stolen',
       'ATM_Robbery_Cases reported', 'ATM_Robbery_Value of property stolen',
       'ATM_Burglary_Cases reported', 'ATM_Burglary_Value of property stolen',
       'ATM_Theft_Cases reported', 'ATM_Theft_Value of property stolen',
       'Bank_Dacoity_Cases reported', 'Bank_Dacoity_Value of property stolen',
       'Bank_Robbery_Cases reported', 'Bank_Robbery_Value of property stolen',
       'Bank_Burglary_Cases reported',
       'Bank_Burglary_Value of property stolen', 'Bank_Theft_Cases reported',
       'Bank_Theft_Value of property stolen', 'CommEst_Dacoity_Cases reported',
       'CommEst_Dacoity_Value of property stolen',
       'CommEst_Robbery_Cases reported',
       'CommEst_Robbery_Value of property stolen',
       'CommEst_Burglary_Cases reported',
       'CommEst_Burglary_Value of property stolen',
       'CommEst_Theft_Cases reported',
       'CommEst_Theft_Value of property stolen',
       'OtherPlaces_Dacoity_Cases reported',
       'OtherPlaces_Dacoity_Value of property stolen',
       'OtherPlaces_Robbery_Cases reported',
       'OtherPlaces_Robbery_Value of property stolen',
       'OtherPlaces_Burglary_Cases reported',
       'OtherPlaces_Burglary_Value of property stolen',
       'OtherPlaces_Theft_Cases reported',
       'OtherPlaces_Theft_Value of property stolen',
       'Total_Dacoity_Cases reported',
       'Total_Dacoity_Value of property stolen',
       'Total_Robbery_Cases reported',
       'Total_Robbery_Value of property stolen',
       'Total_Burglary_Cases reported',
       'Total_Burglary_Value of property stolen', 'Total_Theft_Cases reported',
       'Total_Theft_Value of property stolen'],
      dtype='object')

In [487]:
pc14['Residence_Dacoity_Cases reported']=pc14['Residence_Dacoity_Cases reported']+pc14['Residence_Dacoity_Value of property stolen']

In [488]:
pc14.drop('Residence_Dacoity_Value of property stolen',inplace=True,axis=1)

In [489]:
pc14['Residence_Robbery_Cases reported']=pc14['Residence_Robbery_Cases reported']+pc14['Residence_Robbery_Value of property stolen']

In [490]:
pc14.drop('Residence_Robbery_Value of property stolen',inplace=True,axis=1)

In [491]:
pc14['Residence_Burglary_Cases reported']=pc14['Residence_Burglary_Cases reported']+pc14['Residence_Burglary_Value of property stolen']
pc14.drop('Residence_Burglary_Value of property stolen',inplace=True,axis=1)

In [492]:
pc14['Residence_Theft_Cases reported']=pc14['Residence_Theft_Cases reported']+pc14['Residence_Theft_Value of property stolen']
pc14.drop('Residence_Theft_Value of property stolen',inplace=True,axis=1)

In [493]:
pc14['Highways_Dacoity_Cases reported']=pc14['Highways_Dacoity_Cases reported']+pc14['Highways_Dacoity_Value of property stolen']
pc14.drop('Highways_Dacoity_Value of property stolen',inplace=True,axis=1)

In [494]:
pc14['Highways_Robbery_Cases reported']=pc14['Highways_Robbery_Cases reported']+pc14['Highways_Robbery_Value of property stolen']
pc14.drop('Highways_Robbery_Value of property stolen',inplace=True,axis=1)

In [495]:
pc14['Highways_Burglary_Cases reported']=pc14['Highways_Burglary_Cases reported']+pc14['Highways_Burglary_Value of property stolen']
pc14.drop('Highways_Burglary_Value of property stolen',inplace=True,axis=1)

In [496]:
pc14['Highways_Theft_Cases reported']=pc14['Highways_Theft_Cases reported']+pc14['Highways_Theft_Value of property stolen']
pc14.drop('Highways_Theft_Value of property stolen',inplace=True,axis=1)

In [497]:
pc14['RiverOrSea_Dacoity_Cases reported']=pc14['RiverOrSea_Dacoity_Cases reported']+pc14['RiverOrSea_Dacoity_Value of property stolen']
pc14.drop('RiverOrSea_Dacoity_Value of property stolen',inplace=True,axis=1)
pc14['RiverOrSea_Robbery_Cases reported']=pc14['RiverOrSea_Robbery_Cases reported']+pc14['RiverOrSea_Robbery_Value of property stolen']
pc14.drop('RiverOrSea_Robbery_Value of property stolen',inplace=True,axis=1)
pc14['RiverOrSea_Burglary_Cases reported']=pc14['RiverOrSea_Burglary_Cases reported']+pc14['RiverOrSea_Burglary_Value of property stolen']
pc14.drop('RiverOrSea_Burglary_Value of property stolen',inplace=True,axis=1)
pc14['RiverOrSea_Theft_Cases reported']=pc14['RiverOrSea_Theft_Cases reported']+pc14['RiverOrSea_Theft_Value of property stolen']
pc14.drop('RiverOrSea_Theft_Value of property stolen',inplace=True,axis=1)

In [498]:
pc14['Railways_Dacoity_Cases reported']=pc14['Railways_Dacoity_Cases reported']+pc14['Railways_Dacoity_Value of property stolen']
pc14.drop('Railways_Dacoity_Value of property stolen',inplace=True,axis=1)
pc14['Railways_Robbery_Cases reported']=pc14['Railways_Robbery_Cases reported']+pc14['Railways_Robbery_Value of property stolen']
pc14.drop('Railways_Robbery_Value of property stolen',inplace=True,axis=1)
pc14['Railways_Burglary_Cases reported']=pc14['Railways_Burglary_Cases reported']+pc14['Railways_Burglary_Value of property stolen']
pc14.drop('Railways_Burglary_Value of property stolen',inplace=True,axis=1)
pc14['Railways_Theft_Cases reported']=pc14['Railways_Theft_Cases reported']+pc14['Railways_Theft_Value of property stolen']
pc14.drop('Railways_Theft_Value of property stolen',inplace=True,axis=1)

In [499]:
len(pc14.columns)

66

In [500]:
pc14['Religious Places_Dacoity_Cases reported']=pc14['Religious Places_Dacoity_Cases reported']+pc14['Religious Places_Dacoity_Value of property stolen']
pc14.drop('Religious Places_Dacoity_Value of property stolen',inplace=True,axis=1)
pc14['Religious Places_Robbery_Cases reported']=pc14['Religious Places_Robbery_Cases reported']+pc14['Religious Places_Robbery_Value of property stolen']
pc14.drop('Religious Places_Robbery_Value of property stolen',inplace=True,axis=1)
pc14['Religious Places_Burglary_Cases reported']=pc14['Religious Places_Burglary_Cases reported']+pc14['Religious Places_Burglary_Value of property stolen']
pc14.drop('Religious Places_Burglary_Value of property stolen',inplace=True,axis=1)
pc14['Religious Places_Theft_Cases reported']=pc14['Religious Places_Theft_Cases reported']+pc14['Religious Places_Theft_Value of property stolen']
pc14.drop('Religious Places_Theft_Value of property stolen',inplace=True,axis=1)
pc14['ATM_Dacoity_Cases reported']=pc14['ATM_Dacoity_Cases reported']+pc14['ATM_Dacoity_Value of property stolen']
pc14.drop('ATM_Dacoity_Value of property stolen',inplace=True,axis=1)
pc14['ATM_Robbery_Cases reported']=pc14['ATM_Robbery_Cases reported']+pc14['ATM_Robbery_Value of property stolen']
pc14.drop('ATM_Robbery_Value of property stolen',inplace=True,axis=1)
pc14['ATM_Burglary_Cases reported']=pc14['ATM_Burglary_Cases reported']+pc14['ATM_Burglary_Value of property stolen']
pc14.drop('ATM_Burglary_Value of property stolen',inplace=True,axis=1)
pc14['ATM_Theft_Cases reported']=pc14['ATM_Theft_Cases reported']+pc14['ATM_Theft_Value of property stolen']

In [501]:
pc14.drop( 'ATM_Theft_Value of property stolen',inplace=True,axis=1)

In [502]:
len(pc14.columns)

58

In [503]:
pc14['Bank_Dacoity_Cases reported']=pc14['Bank_Dacoity_Cases reported']+pc14['Bank_Dacoity_Value of property stolen']
pc14.drop('Bank_Dacoity_Value of property stolen',inplace=True,axis=1)
pc14['Bank_Robbery_Cases reported']=pc14['Bank_Robbery_Cases reported']+pc14['Bank_Robbery_Value of property stolen']
pc14.drop('Bank_Robbery_Value of property stolen',inplace=True,axis=1)
pc14['Bank_Burglary_Cases reported']=pc14['Bank_Burglary_Cases reported']+pc14['Bank_Burglary_Value of property stolen']
pc14.drop('Bank_Burglary_Value of property stolen', inplace=True,axis=1)
pc14['Bank_Theft_Cases reported']=pc14['Bank_Theft_Cases reported']+pc14['Bank_Theft_Value of property stolen']
pc14.drop('Bank_Theft_Value of property stolen',inplace=True,axis=1)
pc14['CommEst_Dacoity_Cases reported']=pc14['CommEst_Dacoity_Cases reported']+pc14['CommEst_Dacoity_Value of property stolen']
pc14.drop('CommEst_Dacoity_Value of property stolen',inplace=True,axis=1)
pc14['CommEst_Robbery_Cases reported']=pc14['CommEst_Robbery_Cases reported']+pc14['CommEst_Robbery_Value of property stolen']
pc14.drop('CommEst_Robbery_Value of property stolen',inplace=True,axis=1)
pc14['CommEst_Burglary_Cases reported']=pc14['CommEst_Burglary_Cases reported']+pc14['CommEst_Burglary_Value of property stolen']
pc14.drop('CommEst_Burglary_Value of property stolen',inplace=True,axis=1)
pc14['CommEst_Theft_Cases reported']=pc14['CommEst_Theft_Cases reported']+pc14['CommEst_Theft_Value of property stolen']
pc14.drop('CommEst_Theft_Value of property stolen',inplace=True,axis=1)
pc14['OtherPlaces_Dacoity_Cases reported']=pc14['OtherPlaces_Dacoity_Cases reported']+pc14['OtherPlaces_Dacoity_Value of property stolen']
pc14.drop('OtherPlaces_Dacoity_Value of property stolen',inplace=True,axis=1)
pc14['OtherPlaces_Robbery_Cases reported']=pc14['OtherPlaces_Robbery_Cases reported']+pc14['OtherPlaces_Robbery_Value of property stolen']
pc14.drop('OtherPlaces_Robbery_Value of property stolen',inplace=True,axis=1)
pc14['OtherPlaces_Burglary_Cases reported']=pc14['OtherPlaces_Burglary_Cases reported']+pc14['OtherPlaces_Burglary_Value of property stolen']
pc14.drop('OtherPlaces_Burglary_Value of property stolen',inplace=True,axis=1)
pc14['OtherPlaces_Theft_Cases reported']=pc14['OtherPlaces_Theft_Cases reported']+pc14['OtherPlaces_Theft_Value of property stolen']
pc14.drop('OtherPlaces_Theft_Value of property stolen',inplace=True,axis=1)
pc14['Total_Dacoity_Cases reported']=pc14['Total_Dacoity_Cases reported']+pc14['Total_Dacoity_Value of property stolen']
pc14.drop('Total_Dacoity_Value of property stolen',inplace=True,axis=1)
pc14['Total_Robbery_Cases reported']=pc14['Total_Robbery_Cases reported']+pc14['Total_Robbery_Value of property stolen']
pc14.drop('Total_Robbery_Value of property stolen',inplace=True,axis=1)
pc14['Total_Burglary_Cases reported']=pc14['Total_Burglary_Cases reported']+pc14['Total_Burglary_Value of property stolen']
pc14.drop('Total_Burglary_Value of property stolen', inplace=True,axis=1)
pc14['Total_Theft_Cases reported']=pc14['Total_Theft_Cases reported']+pc14['Total_Theft_Value of property stolen']
pc14.drop('Total_Theft_Value of property stolen',inplace=True,axis=1)

In [504]:
pc14.columns

Index(['States/UTs', 'Year', 'Residence_Dacoity_Cases reported',
       'Residence_Robbery_Cases reported', 'Residence_Burglary_Cases reported',
       'Residence_Theft_Cases reported', 'Highways_Dacoity_Cases reported',
       'Highways_Robbery_Cases reported', 'Highways_Burglary_Cases reported',
       'Highways_Theft_Cases reported', 'RiverOrSea_Dacoity_Cases reported',
       'RiverOrSea_Robbery_Cases reported',
       'RiverOrSea_Burglary_Cases reported', 'RiverOrSea_Theft_Cases reported',
       'Railways_Dacoity_Cases reported', 'Railways_Robbery_Cases reported',
       'Railways_Burglary_Cases reported', 'Railways_Theft_Cases reported',
       'Religious Places_Dacoity_Cases reported',
       'Religious Places_Robbery_Cases reported',
       'Religious Places_Burglary_Cases reported',
       'Religious Places_Theft_Cases reported', 'ATM_Dacoity_Cases reported',
       'ATM_Robbery_Cases reported', 'ATM_Burglary_Cases reported',
       'ATM_Theft_Cases reported', 'Bank_Dacoity_Cases reported',
       'Bank_Robbery_Cases reported', 'Bank_Burglary_Cases reported',
       'Bank_Theft_Cases reported', 'CommEst_Dacoity_Cases reported',
       'CommEst_Robbery_Cases reported', 'CommEst_Burglary_Cases reported',
       'CommEst_Theft_Cases reported', 'OtherPlaces_Dacoity_Cases reported',
       'OtherPlaces_Robbery_Cases reported',
       'OtherPlaces_Burglary_Cases reported',
       'OtherPlaces_Theft_Cases reported', 'Total_Dacoity_Cases reported',
       'Total_Robbery_Cases reported', 'Total_Burglary_Cases reported',
       'Total_Theft_Cases reported'],
      dtype='object')

In [505]:
dfPc.columns

Index(['STATE/UT', 'YEAR', 'RESIDENTIAL PREMISES - Dacoity',
       'RESIDENTIAL PREMISES - Robbery', 'RESIDENTIAL PREMISES - Burglary',
       'RESIDENTIAL PREMISES - Theft', 'HIGHWAYS - Dacoity',
       'HIGHWAYS - Robbery', 'HIGHWAYS - Burglary', 'HIGHWAYS - Theft',
       'RIVER and SEA - Dacoity', 'RIVER and SEA - Robbery',
       'RIVER and SEA - Burglary', 'RIVER and SEA - Theft',
       'RAILWAYS - Dacoity', 'RAILWAYS - Robbery', 'RAILWAYS - Burglary',
       'RAILWAYS - Theft', 'BANKS - Dacoity', 'BANKS - Robbery',
       'BANKS - Burglary', 'BANKS - Theft',
       'COMMERCIAL ESTABLISHMENTS - Dacoity',
       'COMMERCIAL ESTABLISHMENTS - Robbery',
       'COMMERCIAL ESTABLISHMENTS - Burglary',
       'COMMERCIAL ESTABLISHMENTS - Theft', 'OTHER PLACES - Dacoity',
       'OTHER PLACES - Robbery', 'OTHER PLACES - Burglary',
       'OTHER PLACES - Theft', 'TOTAL - Dacoity', 'TOTAL - Robbery',
       'TOTAL - Burglary', 'TOTAL - Theft'],
      dtype='object')

In [506]:
pc14.columns=pc14.columns.str.upper()

In [507]:
pc14.columns

Index(['STATES/UTS', 'YEAR', 'RESIDENCE_DACOITY_CASES REPORTED',
       'RESIDENCE_ROBBERY_CASES REPORTED', 'RESIDENCE_BURGLARY_CASES REPORTED',
       'RESIDENCE_THEFT_CASES REPORTED', 'HIGHWAYS_DACOITY_CASES REPORTED',
       'HIGHWAYS_ROBBERY_CASES REPORTED', 'HIGHWAYS_BURGLARY_CASES REPORTED',
       'HIGHWAYS_THEFT_CASES REPORTED', 'RIVERORSEA_DACOITY_CASES REPORTED',
       'RIVERORSEA_ROBBERY_CASES REPORTED',
       'RIVERORSEA_BURGLARY_CASES REPORTED', 'RIVERORSEA_THEFT_CASES REPORTED',
       'RAILWAYS_DACOITY_CASES REPORTED', 'RAILWAYS_ROBBERY_CASES REPORTED',
       'RAILWAYS_BURGLARY_CASES REPORTED', 'RAILWAYS_THEFT_CASES REPORTED',
       'RELIGIOUS PLACES_DACOITY_CASES REPORTED',
       'RELIGIOUS PLACES_ROBBERY_CASES REPORTED',
       'RELIGIOUS PLACES_BURGLARY_CASES REPORTED',
       'RELIGIOUS PLACES_THEFT_CASES REPORTED', 'ATM_DACOITY_CASES REPORTED',
       'ATM_ROBBERY_CASES REPORTED', 'ATM_BURGLARY_CASES REPORTED',
       'ATM_THEFT_CASES REPORTED', 'BANK_DACOITY_CASES REPORTED',
       'BANK_ROBBERY_CASES REPORTED', 'BANK_BURGLARY_CASES REPORTED',
       'BANK_THEFT_CASES REPORTED', 'COMMEST_DACOITY_CASES REPORTED',
       'COMMEST_ROBBERY_CASES REPORTED', 'COMMEST_BURGLARY_CASES REPORTED',
       'COMMEST_THEFT_CASES REPORTED', 'OTHERPLACES_DACOITY_CASES REPORTED',
       'OTHERPLACES_ROBBERY_CASES REPORTED',
       'OTHERPLACES_BURGLARY_CASES REPORTED',
       'OTHERPLACES_THEFT_CASES REPORTED', 'TOTAL_DACOITY_CASES REPORTED',
       'TOTAL_ROBBERY_CASES REPORTED', 'TOTAL_BURGLARY_CASES REPORTED',
       'TOTAL_THEFT_CASES REPORTED'],
      dtype='object')

In [508]:
pc14.rename(columns = {'STATE/UT':'STATE/UT', 'RESIDENCE_DACOITY_CASES REPORTED':'RESIDENTIAL PREMISES - Dacoity','RESIDENCE_ROBBERY_CASES REPORTED':'RESIDENTIAL PREMISES - Robbery','RESIDENCE_BURGLARY_CASES REPORTED':'RESIDENTIAL PREMISES - Burglary',
                      'RESIDENCE_THEFT_CASES REPORTED':'RESIDENTIAL PREMISES - Theft','HIGHWAYS_DACOITY_CASES REPORTED':'HIGHWAYS - Dacoity',
                      'HIGHWAYS_ROBBERY_CASES REPORTED':'HIGHWAYS - Robbery','HIGHWAYS_BURGLARY_CASES REPORTED':'HIGHWAYS - Burglary',
                      'HIGHWAYS_THEFT_CASES REPORTED':'HIGHWAYS - Theft','RIVERORSEA_DACOITY_CASES REPORTED':'RIVER and SEA - Dacoity',
                      'RIVERORSEA_ROBBERY_CASES REPORTED':'RIVER and SEA - Robbery','RIVERORSEA_BURGLARY_CASES REPORTED':'RIVER and SEA - Burglary',
                      'RIVERORSEA_THEFT_CASES REPORTED':'RIVER and SEA - Theft','RAILWAYS_DACOITY_CASES REPORTED':'RAILWAYS - Dacoity','RAILWAYS_ROBBERY_CASES REPORTED':'RAILWAYS - Robbery',
                      'RAILWAYS_BURGLARY_CASES REPORTED':'RAILWAYS - Burglary','RAILWAYS_THEFT_CASES REPORTED':'RAILWAYS - Theft',
                      'BANK_DACOITY_CASES REPORTED':'BANKS - Dacoity','BANK_ROBBERY_CASES REPORTED':'BANKS - Robbery',
                      'BANK_BURGLARY_CASES REPORTED':'BANKS - Burglary','BANK_THEFT_CASES REPORTED':'BANKS - Theft',
                      'COMMEST_DACOITY_CASES REPORTED':'COMMERCIAL ESTABLISHMENTS - Dacoity','COMMEST_ROBBERY_CASES REPORTED':'COMMERCIAL ESTABLISHMENTS - Robbery',
                      'COMMEST_BURGLARY_CASES REPORTED':'COMMERCIAL ESTABLISHMENTS - Burglary','COMMEST_THEFT_CASES REPORTED':'COMMERCIAL ESTABLISHMENTS - Theft',
                      'OTHERPLACES_DACOITY_CASES REPORTED':'OTHER PLACES - Dacoity','OTHERPLACES_ROBBERY_CASES REPORTED':'OTHER PLACES - Robbery',
                      'OTHERPLACES_BURGLARY_CASES REPORTED':'OTHER PLACES - Burglary','OTHERPLACES_THEFT_CASES REPORTED':'OTHER PLACES - Theft',
                      'TOTAL_DACOITY_CASES REPORTED':'TOTAL - Dacoity','TOTAL_ROBBERY_CASES REPORTED':'TOTAL - Robbery',
                      'TOTAL_BURGLARY_CASES REPORTED':'TOTAL - Burglary','TOTAL_THEFT_CASES REPORTED':'TOTAL - Theft'}, inplace = True)

In [509]:
pc14.columns

Index(['STATES/UTS', 'YEAR', 'RESIDENTIAL PREMISES - Dacoity',
       'RESIDENTIAL PREMISES - Robbery', 'RESIDENTIAL PREMISES - Burglary',
       'RESIDENTIAL PREMISES - Theft', 'HIGHWAYS - Dacoity',
       'HIGHWAYS - Robbery', 'HIGHWAYS - Burglary', 'HIGHWAYS - Theft',
       'RIVER and SEA - Dacoity', 'RIVER and SEA - Robbery',
       'RIVER and SEA - Burglary', 'RIVER and SEA - Theft',
       'RAILWAYS - Dacoity', 'RAILWAYS - Robbery', 'RAILWAYS - Burglary',
       'RAILWAYS - Theft', 'RELIGIOUS PLACES_DACOITY_CASES REPORTED',
       'RELIGIOUS PLACES_ROBBERY_CASES REPORTED',
       'RELIGIOUS PLACES_BURGLARY_CASES REPORTED',
       'RELIGIOUS PLACES_THEFT_CASES REPORTED', 'ATM_DACOITY_CASES REPORTED',
       'ATM_ROBBERY_CASES REPORTED', 'ATM_BURGLARY_CASES REPORTED',
       'ATM_THEFT_CASES REPORTED', 'BANKS - Dacoity', 'BANKS - Robbery',
       'BANKS - Burglary', 'BANKS - Theft',
       'COMMERCIAL ESTABLISHMENTS - Dacoity',
       'COMMERCIAL ESTABLISHMENTS - Robbery',
       'COMMERCIAL ESTABLISHMENTS - Burglary',
       'COMMERCIAL ESTABLISHMENTS - Theft', 'OTHER PLACES - Dacoity',
       'OTHER PLACES - Robbery', 'OTHER PLACES - Burglary',
       'OTHER PLACES - Theft', 'TOTAL - Dacoity', 'TOTAL - Robbery',
       'TOTAL - Burglary', 'TOTAL - Theft'],
      dtype='object')

In [510]:
pcF=pd.concat([dfPc, pc14], axis=0, ignore_index=True)

In [511]:
pcF

,STATE/UT,YEAR,RESIDENTIAL PREMISES - Dacoity,RESIDENTIAL PREMISES - Robbery,RESIDENTIAL PREMISES - Burglary,RESIDENTIAL PREMISES - Theft,HIGHWAYS - Dacoity,HIGHWAYS - Robbery,HIGHWAYS - Burglary,HIGHWAYS - Theft,...,TOTAL - Theft,STATES/UTS,RELIGIOUS PLACES_DACOITY_CASES REPORTED,RELIGIOUS PLACES_ROBBERY_CASES REPORTED,RELIGIOUS PLACES_BURGLARY_CASES REPORTED,RELIGIOUS PLACES_THEFT_CASES REPORTED,ATM_DACOITY_CASES REPORTED,ATM_ROBBERY_CASES REPORTED,ATM_BURGLARY_CASES REPORTED,ATM_THEFT_CASES REPORTED
0,ANDHRA PRADESH,2001,100,177,5158,4257,57,172,31,74,...,16751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ARUNACHAL PRADESH,2001,9,26,99,131,0,0,0,8,...,443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ASSAM,2001,381,191,1695,2901,46,136,7,87,...,5367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BIHAR,2001,818,326,2486,4741,162,826,0,257,...,9701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CHHATTISGARH,2001,54,42,3336,1417,10,38,12,72,...,4812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,NaN,2014,0,0,10,671912,0,0,0,0,...,671912,Lakshadweep,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
529,NaN,2014,200001,1075003,7466040,2900778,252002,110002,90002,7596928,...,20538576,Puducherry,0.0,0.0,11002.0,95005.0,0.0,0.0,772508.0,0.0
530,NaN,2014,370484467,318622764,5302469296,5223603572,587281457,1243496044,39418960,2516350916,...,22747204570,Total (States),573508.0,11846064.0,63915550.5,81635051.0,1875008.0,2229565.0,39470117.0,31233281.0
531,NaN,2014,2051945,36560944,648857341,612799725,125289838,198351620,2277027,1175780869,...,3177564805,Total (UTs),0.0,74950.0,409027.0,2353509.0,0.0,50001.0,1169616.0,2874900.0
532,NaN,2014,372536412,355183708,5951326637,5836403297,712571295,1441847664,41695987,3692131785,...,25924769375,Total (All India),573508.0,11921014.0,64324577.5,83988560.0,1875008.0,2279566.0,40639733.0,34108181.0

In [512]:
pcF["STATE/UT"]=pcF["STATE/UT"].str.upper()

In [513]:
pcF.columns

Index(['STATE/UT', 'YEAR', 'RESIDENTIAL PREMISES - Dacoity',
       'RESIDENTIAL PREMISES - Robbery', 'RESIDENTIAL PREMISES - Burglary',
       'RESIDENTIAL PREMISES - Theft', 'HIGHWAYS - Dacoity',
       'HIGHWAYS - Robbery', 'HIGHWAYS - Burglary', 'HIGHWAYS - Theft',
       'RIVER and SEA - Dacoity', 'RIVER and SEA - Robbery',
       'RIVER and SEA - Burglary', 'RIVER and SEA - Theft',
       'RAILWAYS - Dacoity', 'RAILWAYS - Robbery', 'RAILWAYS - Burglary',
       'RAILWAYS - Theft', 'BANKS - Dacoity', 'BANKS - Robbery',
       'BANKS - Burglary', 'BANKS - Theft',
       'COMMERCIAL ESTABLISHMENTS - Dacoity',
       'COMMERCIAL ESTABLISHMENTS - Robbery',
       'COMMERCIAL ESTABLISHMENTS - Burglary',
       'COMMERCIAL ESTABLISHMENTS - Theft', 'OTHER PLACES - Dacoity',
       'OTHER PLACES - Robbery', 'OTHER PLACES - Burglary',
       'OTHER PLACES - Theft', 'TOTAL - Dacoity', 'TOTAL - Robbery',
       'TOTAL - Burglary', 'TOTAL - Theft', 'STATES/UTS',
       'RELIGIOUS PLACES_DACOITY_CASES REPORTED',
       'RELIGIOUS PLACES_ROBBERY_CASES REPORTED',
       'RELIGIOUS PLACES_BURGLARY_CASES REPORTED',
       'RELIGIOUS PLACES_THEFT_CASES REPORTED', 'ATM_DACOITY_CASES REPORTED',
       'ATM_ROBBERY_CASES REPORTED', 'ATM_BURGLARY_CASES REPORTED',
       'ATM_THEFT_CASES REPORTED'],
      dtype='object')

In [514]:
pcF=pcF.fillna(0)

In [328]:
pcF.to_csv("placeWiseProcessed.csv",index=False)

In [638]:
dfF

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,OTHER THEFTS,FORGERY,COUNTERFEITING,IMPORTATION OF GIRLS FROM FOREIGN COUNTRY
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,92,...,34.0,175,0.0,181,1518,4154,0.0,0.0,0.0,0.0
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,106,...,24.0,154,0.0,270,754,4125,0.0,0.0,0.0,0.0
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,118,...,83.0,186,0.0,404,1262,5818,0.0,0.0,0.0,0.0
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,50,...,38.0,57,0.0,233,1181,3140,0.0,0.0,0.0,0.0
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,98,...,58.0,247,0.0,431,2313,6507,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10673,LAKSHADWEEP,LAKSHADWEEP,2014,0,0,0,3,0,1,0,...,0.0,0,0.0,1,30,81,15.0,2.0,0.0,0.0
10674,LAKSHADWEEP,TOTAL,2014,0,0,0,3,0,1,0,...,0.0,0,0.0,1,30,81,15.0,2.0,0.0,0.0
10675,PUDUCHERRY,KARAIKAL,2014,6,1,0,9,0,3,2,...,0.0,1,0.0,292,322,671,22.0,5.0,0.0,0.0
10676,PUDUCHERRY,PUDUCHERRY,2014,19,14,3,21,1,8,24,...,0.0,3,0.0,1317,1014,2913,117.0,8.0,0.0,0.0
10677,PUDUCHERRY,TOTAL,2014,25,15,3,30,1,11,26,...,0.0,4,0.0,1609,1336,3584,139.0,13.0,0.0,0.0

In [657]:
temp = dfF

In [658]:
temp

,STATE/UT,DISTRICT,YEAR,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,OTHER THEFTS,FORGERY,COUNTERFEITING,IMPORTATION OF GIRLS FROM FOREIGN COUNTRY
0,ANDHRA PRADESH,ADILABAD,2001,101,60,17,50,0,50,92,...,34.0,175,0.0,181,1518,4154,0.0,0.0,0.0,0.0
1,ANDHRA PRADESH,ANANTAPUR,2001,151,125,1,23,0,23,106,...,24.0,154,0.0,270,754,4125,0.0,0.0,0.0,0.0
2,ANDHRA PRADESH,CHITTOOR,2001,101,57,2,27,0,27,118,...,83.0,186,0.0,404,1262,5818,0.0,0.0,0.0,0.0
3,ANDHRA PRADESH,CUDDAPAH,2001,80,53,1,20,0,20,50,...,38.0,57,0.0,233,1181,3140,0.0,0.0,0.0,0.0
4,ANDHRA PRADESH,EAST GODAVARI,2001,82,67,1,23,0,23,98,...,58.0,247,0.0,431,2313,6507,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10673,LAKSHADWEEP,LAKSHADWEEP,2014,0,0,0,3,0,1,0,...,0.0,0,0.0,1,30,81,15.0,2.0,0.0,0.0
10674,LAKSHADWEEP,TOTAL,2014,0,0,0,3,0,1,0,...,0.0,0,0.0,1,30,81,15.0,2.0,0.0,0.0
10675,PUDUCHERRY,KARAIKAL,2014,6,1,0,9,0,3,2,...,0.0,1,0.0,292,322,671,22.0,5.0,0.0,0.0
10676,PUDUCHERRY,PUDUCHERRY,2014,19,14,3,21,1,8,24,...,0.0,3,0.0,1317,1014,2913,117.0,8.0,0.0,0.0
10677,PUDUCHERRY,TOTAL,2014,25,15,3,30,1,11,26,...,0.0,4,0.0,1609,1336,3584,139.0,13.0,0.0,0.0

In [641]:
temp[0]=temp[0].apply(lambda x:temp[1]+","+temp[0])

KeyError: 0

In [662]:
temp["STATE/UT"]=temp["DISTRICT"]+ ", "+temp["STATE/UT"]

In [663]:
temp.drop("DISTRICT",inplace=True,axis=1)

In [664]:
temp.drop("YEAR",inplace=True,axis=1)

In [665]:
temp=temp.groupby("STATE/UT").sum()
#grouped_df = temp.groupby('DISTRICT')

#for key, item in grouped_df:
 #   print(grouped_df.get_group(key), "\n\n")
temp=temp/14

In [666]:
temp

,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,OTHER THEFTS,FORGERY,COUNTERFEITING,IMPORTATION OF GIRLS FROM FOREIGN COUNTRY
STATE/UT,,,,,,,,,,,,,,,,,,,,,
"24 PARGANAS NORTH, WEST BENGAL",176.071429,110.142857,75.428571,142.714286,0.0,142.714286,534.142857,19.142857,117.785714,56.071429,...,3.928571,1368.714286,0.571429,13.428571,4613.785714,9728.857143,0.000000,0.0,0.000000,0.0
"24 PARGANAS SOUTH, WEST BENGAL",167.142857,14.642857,40.285714,172.142857,0.0,172.142857,372.285714,15.142857,107.071429,30.928571,...,1.500000,1475.000000,0.214286,34.428571,4795.285714,9748.500000,0.000000,0.0,0.000000,0.0
"A AND N ISLANDS, A & N ISLANDS",1.071429,1.357143,0.071429,0.214286,0.0,0.214286,1.714286,0.357143,0.000000,0.642857,...,0.142857,1.285714,0.000000,0.285714,24.071429,57.642857,0.000000,0.0,0.000000,0.0
"ADILABAD, ANDHRA PRADESH",91.571429,67.214286,11.714286,52.357143,0.0,52.357143,117.000000,5.285714,0.000000,17.928571,...,98.571429,327.857143,0.000000,283.500000,1569.214286,4881.428571,0.000000,0.0,0.000000,0.0
"ADILABAD, TELANGANA",7.214286,5.642857,1.214286,9.928571,0.0,3.000000,6.571429,0.142857,0.000000,0.500000,...,0.000000,27.428571,0.000000,133.357143,167.071429,431.142857,26.357143,0.0,0.642857,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"ZZ TOTAL, TAMIL NADU",138.285714,214.785714,2.357143,65.928571,0.0,65.928571,254.142857,5.928571,3.928571,156.142857,...,22.357143,176.500000,0.000000,1067.428571,9132.142857,14541.357143,0.000000,0.0,0.000000,0.0
"ZZ TOTAL, TRIPURA",10.142857,4.214286,0.071429,16.642857,0.0,16.642857,20.571429,0.642857,0.071429,3.142857,...,0.500000,59.071429,0.000000,0.714286,112.714286,443.571429,0.000000,0.0,0.000000,0.0
"ZZ TOTAL, UTTAR PRADESH",360.500000,375.642857,90.571429,217.857143,0.0,217.857143,1597.571429,42.571429,5.000000,256.500000,...,1.785714,627.214286,0.000000,1024.642857,5731.785714,16174.642857,0.000000,0.0,0.000000,0.0
"ZZ TOTAL, UTTARAKHAND",14.071429,12.928571,3.000000,16.285714,0.0,16.285714,147.428571,1.214286,0.500000,9.857143,...,5.142857,31.071429,0.000000,40.642857,168.357143,681.857143,0.000000,0.0,0.000000,0.0
"ZZ TOTAL, WEST BENGAL",161.714286,251.642857,29.642857,120.357143,0.0,120.357143,653.285714,14.714286,78.500000,46.214286,...,41.214286,1294.000000,0.642857,289.428571,5052.714286,12109.642857,0.000000,0.0,0.000000,0.0

In [348]:
temp=dfF.groupby("DISTRICT").sum()

In [668]:
temp.to_csv("crimeAM.csv")

In [355]:
temp.describe()

,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,OTHER THEFTS,FORGERY,COUNTERFEITING,IMPORTATION OF GIRLS FROM FOREIGN COUNTRY
count,10678.000000,10678.000000,10678.000000,10678.000000,10678.000000,10678.000000,10678.000000,10678.000000,10678.000000,10678.000000,...,10678.000000,10678.000000,10678.000000,10678.00000,10678.000000,10678.000000,10678.000000,10678.000000,10678.000000,10678.000000
mean,88.008616,80.406818,10.435288,73.644503,0.042330,58.783855,187.574452,13.625398,7.105263,59.614909,...,25.593370,209.258288,0.172879,335.67316,2217.561154,5515.511332,48.029406,2.110508,1.053568,0.002622
std,323.658451,317.038205,63.414457,361.340331,1.898937,219.518150,800.409127,59.919671,43.270258,267.635862,...,163.715213,906.342476,2.226957,2123.31822,8217.397429,19397.649619,792.894065,49.644371,17.981502,0.095769
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,18.000000,10.000000,0.000000,9.000000,0.000000,8.000000,20.000000,1.000000,0.000000,6.000000,...,0.000000,11.000000,0.000000,7.00000,260.000000,861.000000,0.000000,0.000000,0.000000,0.000000
50%,37.000000,28.000000,2.000000,23.000000,0.000000,22.000000,56.000000,3.000000,0.000000,17.000000,...,1.000000,50.000000,0.000000,80.00000,752.000000,2159.000000,0.000000,0.000000,0.000000,0.000000
75%,66.000000,58.000000,6.000000,48.000000,0.000000,45.000000,128.000000,10.000000,2.000000,38.000000,...,11.000000,144.000000,0.000000,207.00000,1644.750000,4078.000000,0.000000,0.000000,0.000000,0.000000
max,7601.000000,7964.000000,1918.000000,15284.000000,189.000000,5360.000000,24722.000000,1770.000000,1263.000000,9746.000000,...,4970.000000,23564.000000,83.000000,116038.00000,127869.000000,272423.000000,55369.000000,4316.000000,1077.000000,5.000000

In [673]:
crime=np.array(['MURDER',
 'ATTEMPT TO MURDER',
 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',
 'RAPE',
 'CUSTODIAL RAPE',
 'OTHER RAPE',
 'KIDNAPPING & ABDUCTION',
 'DACOITY',
 'PREPARATION AND ASSEMBLY FOR DACOITY',
 'ROBBERY',
 'BURGLARY',
 'THEFT',
 'AUTO THEFT',
 'OTHER THEFT',
 'RIOTS',
 'CRIMINAL BREACH OF TRUST',
 'CHEATING',
 'COUNTERFIETING',
 'ARSON',
 'HURT/GREVIOUS HURT',
 'DOWRY DEATHS',
 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
 'INSULT TO MODESTY OF WOMEN',
 'CRUELTY BY HUSBAND OR HIS RELATIVES',
 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
 'CAUSING DEATH BY NEGLIGENCE',
 'OTHER IPC CRIMES',
 'TOTAL IPC CRIMES',
 'OTHER THEFTS',
 'FORGERY',
 'COUNTERFEITING',
 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'])

In [674]:
crime

array(['MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE',
       'CUSTODIAL RAPE', 'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'DACOITY', 'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY',
       'BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFT', 'RIOTS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'COUNTERFIETING', 'ARSON',
       'HURT/GREVIOUS HURT', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES',
       'TOTAL IPC CRIMES', 'OTHER THEFTS', 'FORGERY', 'COUNTERFEITING',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'], dtype='<U51')

In [675]:
human_class=np.array(['FEMALE INFANT',
 'FEMALE KID',
 'FEMALE TEEN',
 'FEMALE ADULT',
 'FEMALE OLD',
 'MALE INFANT',
 'MALE KID',
 'MALE TEEN',
 'MALE ADULT',
 'MALE OLD'])

In [676]:
human_class

array(['FEMALE INFANT', 'FEMALE KID', 'FEMALE TEEN', 'FEMALE ADULT',
       'FEMALE OLD', 'MALE INFANT', 'MALE KID', 'MALE TEEN', 'MALE ADULT',
       'MALE OLD'], dtype='<U13')

In [677]:
cp=[]
for i in human_class:
    for j in crime:
        cp.append((i,j))

In [678]:
cp

[('FEMALE INFANT', 'MURDER'),
 ('FEMALE INFANT', 'ATTEMPT TO MURDER'),
 ('FEMALE INFANT', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('FEMALE INFANT', 'RAPE'),
 ('FEMALE INFANT', 'CUSTODIAL RAPE'),
 ('FEMALE INFANT', 'OTHER RAPE'),
 ('FEMALE INFANT', 'KIDNAPPING & ABDUCTION'),
 ('FEMALE INFANT', 'DACOITY'),
 ('FEMALE INFANT', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('FEMALE INFANT', 'ROBBERY'),
 ('FEMALE INFANT', 'BURGLARY'),
 ('FEMALE INFANT', 'THEFT'),
 ('FEMALE INFANT', 'AUTO THEFT'),
 ('FEMALE INFANT', 'OTHER THEFT'),
 ('FEMALE INFANT', 'RIOTS'),
 ('FEMALE INFANT', 'CRIMINAL BREACH OF TRUST'),
 ('FEMALE INFANT', 'CHEATING'),
 ('FEMALE INFANT', 'COUNTERFIETING'),
 ('FEMALE INFANT', 'ARSON'),
 ('FEMALE INFANT', 'HURT/GREVIOUS HURT'),
 ('FEMALE INFANT', 'DOWRY DEATHS'),
 ('FEMALE INFANT', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('FEMALE INFANT', 'INSULT TO MODESTY OF WOMEN'),
 ('FEMALE INFANT', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('FEMALE INFANT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('FEMALE INFANT', 'CAUSING DEATH BY NEGLIGENCE'),
 ('FEMALE INFANT', 'OTHER IPC CRIMES'),
 ('FEMALE INFANT', 'TOTAL IPC CRIMES'),
 ('FEMALE INFANT', 'OTHER THEFTS'),
 ('FEMALE INFANT', 'FORGERY'),
 ('FEMALE INFANT', 'COUNTERFEITING'),
 ('FEMALE INFANT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('FEMALE KID', 'MURDER'),
 ('FEMALE KID', 'ATTEMPT TO MURDER'),
 ('FEMALE KID', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('FEMALE KID', 'RAPE'),
 ('FEMALE KID', 'CUSTODIAL RAPE'),
 ('FEMALE KID', 'OTHER RAPE'),
 ('FEMALE KID', 'KIDNAPPING & ABDUCTION'),
 ('FEMALE KID', 'DACOITY'),
 ('FEMALE KID', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('FEMALE KID', 'ROBBERY'),
 ('FEMALE KID', 'BURGLARY'),
 ('FEMALE KID', 'THEFT'),
 ('FEMALE KID', 'AUTO THEFT'),
 ('FEMALE KID', 'OTHER THEFT'),
 ('FEMALE KID', 'RIOTS'),
 ('FEMALE KID', 'CRIMINAL BREACH OF TRUST'),
 ('FEMALE KID', 'CHEATING'),
 ('FEMALE KID', 'COUNTERFIETING'),
 ('FEMALE KID', 'ARSON'),
 ('FEMALE KID', 'HURT/GREVIOUS HURT'),
 ('FEMALE KID', 'DOWRY DEATHS'),
 ('FEMALE KID', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('FEMALE KID', 'INSULT TO MODESTY OF WOMEN'),
 ('FEMALE KID', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('FEMALE KID', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('FEMALE KID', 'CAUSING DEATH BY NEGLIGENCE'),
 ('FEMALE KID', 'OTHER IPC CRIMES'),
 ('FEMALE KID', 'TOTAL IPC CRIMES'),
 ('FEMALE KID', 'OTHER THEFTS'),
 ('FEMALE KID', 'FORGERY'),
 ('FEMALE KID', 'COUNTERFEITING'),
 ('FEMALE KID', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('FEMALE TEEN', 'MURDER'),
 ('FEMALE TEEN', 'ATTEMPT TO MURDER'),
 ('FEMALE TEEN', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('FEMALE TEEN', 'RAPE'),
 ('FEMALE TEEN', 'CUSTODIAL RAPE'),
 ('FEMALE TEEN', 'OTHER RAPE'),
 ('FEMALE TEEN', 'KIDNAPPING & ABDUCTION'),
 ('FEMALE TEEN', 'DACOITY'),
 ('FEMALE TEEN', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('FEMALE TEEN', 'ROBBERY'),
 ('FEMALE TEEN', 'BURGLARY'),
 ('FEMALE TEEN', 'THEFT'),
 ('FEMALE TEEN', 'AUTO THEFT'),
 ('FEMALE TEEN', 'OTHER THEFT'),
 ('FEMALE TEEN', 'RIOTS'),
 ('FEMALE TEEN', 'CRIMINAL BREACH OF TRUST'),
 ('FEMALE TEEN', 'CHEATING'),
 ('FEMALE TEEN', 'COUNTERFIETING'),
 ('FEMALE TEEN', 'ARSON'),
 ('FEMALE TEEN', 'HURT/GREVIOUS HURT'),
 ('FEMALE TEEN', 'DOWRY DEATHS'),
 ('FEMALE TEEN', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('FEMALE TEEN', 'INSULT TO MODESTY OF WOMEN'),
 ('FEMALE TEEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('FEMALE TEEN', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('FEMALE TEEN', 'CAUSING DEATH BY NEGLIGENCE'),
 ('FEMALE TEEN', 'OTHER IPC CRIMES'),
 ('FEMALE TEEN', 'TOTAL IPC CRIMES'),
 ('FEMALE TEEN', 'OTHER THEFTS'),
 ('FEMALE TEEN', 'FORGERY'),
 ('FEMALE TEEN', 'COUNTERFEITING'),
 ('FEMALE TEEN', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('FEMALE ADULT', 'MURDER'),
 ('FEMALE ADULT', 'ATTEMPT TO MURDER'),
 ('FEMALE ADULT', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('FEMALE ADULT', 'RAPE'),
 ('FEMALE ADULT', 'CUSTODIAL RAPE'),
 ('FEMALE ADULT', 'OTHER RAPE'),
 ('FEMALE ADULT', 'KIDNAPPING & ABDUCTION'),
 ('FEMALE ADULT', 'DACOITY'),
 ('FEMALE ADULT', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('FEMALE ADULT', 'ROBBERY'),
 ('FEMALE ADULT', 'BURGLARY'),
 ('FEMALE ADULT', 'THEFT'),
 ('FEMALE ADULT', 'AUTO THEFT'),
 ('FEMALE ADULT', 'OTHER THEFT'),
 ('FEMALE ADULT', 'RIOTS'),
 ('FEMALE ADULT', 'CRIMINAL BREACH OF TRUST'),
 ('FEMALE ADULT', 'CHEATING'),
 ('FEMALE ADULT', 'COUNTERFIETING'),
 ('FEMALE ADULT', 'ARSON'),
 ('FEMALE ADULT', 'HURT/GREVIOUS HURT'),
 ('FEMALE ADULT', 'DOWRY DEATHS'),
 ('FEMALE ADULT', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('FEMALE ADULT', 'INSULT TO MODESTY OF WOMEN'),
 ('FEMALE ADULT', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('FEMALE ADULT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('FEMALE ADULT', 'CAUSING DEATH BY NEGLIGENCE'),
 ('FEMALE ADULT', 'OTHER IPC CRIMES'),
 ('FEMALE ADULT', 'TOTAL IPC CRIMES'),
 ('FEMALE ADULT', 'OTHER THEFTS'),
 ('FEMALE ADULT', 'FORGERY'),
 ('FEMALE ADULT', 'COUNTERFEITING'),
 ('FEMALE ADULT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('FEMALE OLD', 'MURDER'),
 ('FEMALE OLD', 'ATTEMPT TO MURDER'),
 ('FEMALE OLD', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('FEMALE OLD', 'RAPE'),
 ('FEMALE OLD', 'CUSTODIAL RAPE'),
 ('FEMALE OLD', 'OTHER RAPE'),
 ('FEMALE OLD', 'KIDNAPPING & ABDUCTION'),
 ('FEMALE OLD', 'DACOITY'),
 ('FEMALE OLD', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('FEMALE OLD', 'ROBBERY'),
 ('FEMALE OLD', 'BURGLARY'),
 ('FEMALE OLD', 'THEFT'),
 ('FEMALE OLD', 'AUTO THEFT'),
 ('FEMALE OLD', 'OTHER THEFT'),
 ('FEMALE OLD', 'RIOTS'),
 ('FEMALE OLD', 'CRIMINAL BREACH OF TRUST'),
 ('FEMALE OLD', 'CHEATING'),
 ('FEMALE OLD', 'COUNTERFIETING'),
 ('FEMALE OLD', 'ARSON'),
 ('FEMALE OLD', 'HURT/GREVIOUS HURT'),
 ('FEMALE OLD', 'DOWRY DEATHS'),
 ('FEMALE OLD', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('FEMALE OLD', 'INSULT TO MODESTY OF WOMEN'),
 ('FEMALE OLD', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('FEMALE OLD', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('FEMALE OLD', 'CAUSING DEATH BY NEGLIGENCE'),
 ('FEMALE OLD', 'OTHER IPC CRIMES'),
 ('FEMALE OLD', 'TOTAL IPC CRIMES'),
 ('FEMALE OLD', 'OTHER THEFTS'),
 ('FEMALE OLD', 'FORGERY'),
 ('FEMALE OLD', 'COUNTERFEITING'),
 ('FEMALE OLD', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('MALE INFANT', 'MURDER'),
 ('MALE INFANT', 'ATTEMPT TO MURDER'),
 ('MALE INFANT', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('MALE INFANT', 'RAPE'),
 ('MALE INFANT', 'CUSTODIAL RAPE'),
 ('MALE INFANT', 'OTHER RAPE'),
 ('MALE INFANT', 'KIDNAPPING & ABDUCTION'),
 ('MALE INFANT', 'DACOITY'),
 ('MALE INFANT', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('MALE INFANT', 'ROBBERY'),
 ('MALE INFANT', 'BURGLARY'),
 ('MALE INFANT', 'THEFT'),
 ('MALE INFANT', 'AUTO THEFT'),
 ('MALE INFANT', 'OTHER THEFT'),
 ('MALE INFANT', 'RIOTS'),
 ('MALE INFANT', 'CRIMINAL BREACH OF TRUST'),
 ('MALE INFANT', 'CHEATING'),
 ('MALE INFANT', 'COUNTERFIETING'),
 ('MALE INFANT', 'ARSON'),
 ('MALE INFANT', 'HURT/GREVIOUS HURT'),
 ('MALE INFANT', 'DOWRY DEATHS'),
 ('MALE INFANT', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('MALE INFANT', 'INSULT TO MODESTY OF WOMEN'),
 ('MALE INFANT', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('MALE INFANT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('MALE INFANT', 'CAUSING DEATH BY NEGLIGENCE'),
 ('MALE INFANT', 'OTHER IPC CRIMES'),
 ('MALE INFANT', 'TOTAL IPC CRIMES'),
 ('MALE INFANT', 'OTHER THEFTS'),
 ('MALE INFANT', 'FORGERY'),
 ('MALE INFANT', 'COUNTERFEITING'),
 ('MALE INFANT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('MALE KID', 'MURDER'),
 ('MALE KID', 'ATTEMPT TO MURDER'),
 ('MALE KID', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('MALE KID', 'RAPE'),
 ('MALE KID', 'CUSTODIAL RAPE'),
 ('MALE KID', 'OTHER RAPE'),
 ('MALE KID', 'KIDNAPPING & ABDUCTION'),
 ('MALE KID', 'DACOITY'),
 ('MALE KID', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('MALE KID', 'ROBBERY'),
 ('MALE KID', 'BURGLARY'),
 ('MALE KID', 'THEFT'),
 ('MALE KID', 'AUTO THEFT'),
 ('MALE KID', 'OTHER THEFT'),
 ('MALE KID', 'RIOTS'),
 ('MALE KID', 'CRIMINAL BREACH OF TRUST'),
 ('MALE KID', 'CHEATING'),
 ('MALE KID', 'COUNTERFIETING'),
 ('MALE KID', 'ARSON'),
 ('MALE KID', 'HURT/GREVIOUS HURT'),
 ('MALE KID', 'DOWRY DEATHS'),
 ('MALE KID', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('MALE KID', 'INSULT TO MODESTY OF WOMEN'),
 ('MALE KID', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('MALE KID', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('MALE KID', 'CAUSING DEATH BY NEGLIGENCE'),
 ('MALE KID', 'OTHER IPC CRIMES'),
 ('MALE KID', 'TOTAL IPC CRIMES'),
 ('MALE KID', 'OTHER THEFTS'),
 ('MALE KID', 'FORGERY'),
 ('MALE KID', 'COUNTERFEITING'),
 ('MALE KID', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('MALE TEEN', 'MURDER'),
 ('MALE TEEN', 'ATTEMPT TO MURDER'),
 ('MALE TEEN', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('MALE TEEN', 'RAPE'),
 ('MALE TEEN', 'CUSTODIAL RAPE'),
 ('MALE TEEN', 'OTHER RAPE'),
 ('MALE TEEN', 'KIDNAPPING & ABDUCTION'),
 ('MALE TEEN', 'DACOITY'),
 ('MALE TEEN', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('MALE TEEN', 'ROBBERY'),
 ('MALE TEEN', 'BURGLARY'),
 ('MALE TEEN', 'THEFT'),
 ('MALE TEEN', 'AUTO THEFT'),
 ('MALE TEEN', 'OTHER THEFT'),
 ('MALE TEEN', 'RIOTS'),
 ('MALE TEEN', 'CRIMINAL BREACH OF TRUST'),
 ('MALE TEEN', 'CHEATING'),
 ('MALE TEEN', 'COUNTERFIETING'),
 ('MALE TEEN', 'ARSON'),
 ('MALE TEEN', 'HURT/GREVIOUS HURT'),
 ('MALE TEEN', 'DOWRY DEATHS'),
 ('MALE TEEN', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('MALE TEEN', 'INSULT TO MODESTY OF WOMEN'),
 ('MALE TEEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('MALE TEEN', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('MALE TEEN', 'CAUSING DEATH BY NEGLIGENCE'),
 ('MALE TEEN', 'OTHER IPC CRIMES'),
 ('MALE TEEN', 'TOTAL IPC CRIMES'),
 ('MALE TEEN', 'OTHER THEFTS'),
 ('MALE TEEN', 'FORGERY'),
 ('MALE TEEN', 'COUNTERFEITING'),
 ('MALE TEEN', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('MALE ADULT', 'MURDER'),
 ('MALE ADULT', 'ATTEMPT TO MURDER'),
 ('MALE ADULT', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('MALE ADULT', 'RAPE'),
 ('MALE ADULT', 'CUSTODIAL RAPE'),
 ('MALE ADULT', 'OTHER RAPE'),
 ('MALE ADULT', 'KIDNAPPING & ABDUCTION'),
 ('MALE ADULT', 'DACOITY'),
 ('MALE ADULT', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('MALE ADULT', 'ROBBERY'),
 ('MALE ADULT', 'BURGLARY'),
 ('MALE ADULT', 'THEFT'),
 ('MALE ADULT', 'AUTO THEFT'),
 ('MALE ADULT', 'OTHER THEFT'),
 ('MALE ADULT', 'RIOTS'),
 ('MALE ADULT', 'CRIMINAL BREACH OF TRUST'),
 ('MALE ADULT', 'CHEATING'),
 ('MALE ADULT', 'COUNTERFIETING'),
 ('MALE ADULT', 'ARSON'),
 ('MALE ADULT', 'HURT/GREVIOUS HURT'),
 ('MALE ADULT', 'DOWRY DEATHS'),
 ('MALE ADULT', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('MALE ADULT', 'INSULT TO MODESTY OF WOMEN'),
 ('MALE ADULT', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('MALE ADULT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('MALE ADULT', 'CAUSING DEATH BY NEGLIGENCE'),
 ('MALE ADULT', 'OTHER IPC CRIMES'),
 ('MALE ADULT', 'TOTAL IPC CRIMES'),
 ('MALE ADULT', 'OTHER THEFTS'),
 ('MALE ADULT', 'FORGERY'),
 ('MALE ADULT', 'COUNTERFEITING'),
 ('MALE ADULT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'),
 ('MALE OLD', 'MURDER'),
 ('MALE OLD', 'ATTEMPT TO MURDER'),
 ('MALE OLD', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER'),
 ('MALE OLD', 'RAPE'),
 ('MALE OLD', 'CUSTODIAL RAPE'),
 ('MALE OLD', 'OTHER RAPE'),
 ('MALE OLD', 'KIDNAPPING & ABDUCTION'),
 ('MALE OLD', 'DACOITY'),
 ('MALE OLD', 'PREPARATION AND ASSEMBLY FOR DACOITY'),
 ('MALE OLD', 'ROBBERY'),
 ('MALE OLD', 'BURGLARY'),
 ('MALE OLD', 'THEFT'),
 ('MALE OLD', 'AUTO THEFT'),
 ('MALE OLD', 'OTHER THEFT'),
 ('MALE OLD', 'RIOTS'),
 ('MALE OLD', 'CRIMINAL BREACH OF TRUST'),
 ('MALE OLD', 'CHEATING'),
 ('MALE OLD', 'COUNTERFIETING'),
 ('MALE OLD', 'ARSON'),
 ('MALE OLD', 'HURT/GREVIOUS HURT'),
 ('MALE OLD', 'DOWRY DEATHS'),
 ('MALE OLD', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY'),
 ('MALE OLD', 'INSULT TO MODESTY OF WOMEN'),
 ('MALE OLD', 'CRUELTY BY HUSBAND OR HIS RELATIVES'),
 ('MALE OLD', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES'),
 ('MALE OLD', 'CAUSING DEATH BY NEGLIGENCE'),
 ('MALE OLD', 'OTHER IPC CRIMES'),
 ('MALE OLD', 'TOTAL IPC CRIMES'),
 ('MALE OLD', 'OTHER THEFTS'),
 ('MALE OLD', 'FORGERY'),
 ('MALE OLD', 'COUNTERFEITING'),
 ('MALE OLD', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY')]

In [ ]:
[('FEMALE INFANT', 'MURDER',0.8),
 ('FEMALE INFANT', 'ATTEMPT TO MURDER',0.8),
 ('FEMALE INFANT', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0.6),
 ('FEMALE INFANT', 'RAPE',0.4),
 ('FEMALE INFANT', 'CUSTODIAL RAPE',0.4),
 ('FEMALE INFANT', 'OTHER RAPE',0),
 ('FEMALE INFANT', 'KIDNAPPING & ABDUCTION',0.8),
 ('FEMALE INFANT', 'DACOITY',0),
 ('FEMALE INFANT', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('FEMALE INFANT', 'ROBBERY',0),
 ('FEMALE INFANT', 'BURGLARY',0),
 ('FEMALE INFANT', 'THEFT',0),
 ('FEMALE INFANT', 'AUTO THEFT',0),
 ('FEMALE INFANT', 'OTHER THEFT',0),
 ('FEMALE INFANT', 'RIOTS',0),
 ('FEMALE INFANT', 'CRIMINAL BREACH OF TRUST',0),
 ('FEMALE INFANT', 'CHEATING',0),
 ('FEMALE INFANT', 'COUNTERFIETING',0),
 ('FEMALE INFANT', 'ARSON',0),
 ('FEMALE INFANT', 'HURT/GREVIOUS HURT',0),
 ('FEMALE INFANT', 'DOWRY DEATHS',0),
 ('FEMALE INFANT', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0),
 ('FEMALE INFANT', 'INSULT TO MODESTY OF WOMEN',0),
 ('FEMALE INFANT', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0),
 ('FEMALE INFANT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('FEMALE INFANT', 'CAUSING DEATH BY NEGLIGENCE',0),
 ('FEMALE INFANT', 'OTHER IPC CRIMES',0),
 ('FEMALE INFANT', 'TOTAL IPC CRIMES',0),
 ('FEMALE INFANT', 'OTHER THEFTS',0),
 ('FEMALE INFANT', 'FORGERY',0),
 ('FEMALE INFANT', 'COUNTERFEITING',0),
 ('FEMALE INFANT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('FEMALE KID', 'MURDER',0.7),
 ('FEMALE KID', 'ATTEMPT TO MURDER',0.6),
 ('FEMALE KID', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0.65),
 ('FEMALE KID', 'RAPE',0.8),
 ('FEMALE KID', 'CUSTODIAL RAPE',0),
 ('FEMALE KID', 'OTHER RAPE',0),
 ('FEMALE KID', 'KIDNAPPING & ABDUCTION',0.8),
 ('FEMALE KID', 'DACOITY',0),
 ('FEMALE KID', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('FEMALE KID', 'ROBBERY',0),
 ('FEMALE KID', 'BURGLARY',0),
 ('FEMALE KID', 'THEFT',0),
 ('FEMALE KID', 'AUTO THEFT',0),
 ('FEMALE KID', 'OTHER THEFT',0),
 ('FEMALE KID', 'RIOTS',0),
 ('FEMALE KID', 'CRIMINAL BREACH OF TRUST',0),
 ('FEMALE KID', 'CHEATING',0),
 ('FEMALE KID', 'COUNTERFIETING',0),
 ('FEMALE KID', 'ARSON',0),
 ('FEMALE KID', 'HURT/GREVIOUS HURT',0),
 ('FEMALE KID', 'DOWRY DEATHS',0),
 ('FEMALE KID', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0),
 ('FEMALE KID', 'INSULT TO MODESTY OF WOMEN',0),
 ('FEMALE KID', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0),
 ('FEMALE KID', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('FEMALE KID', 'CAUSING DEATH BY NEGLIGENCE',0.7),
 ('FEMALE KID', 'OTHER IPC CRIMES',0),
 ('FEMALE KID', 'TOTAL IPC CRIMES',0),
 ('FEMALE KID', 'OTHER THEFTS',0),
 ('FEMALE KID', 'FORGERY',0),
 ('FEMALE KID', 'COUNTERFEITING',0),
 ('FEMALE KID', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('FEMALE TEEN', 'MURDER',0.8),
 ('FEMALE TEEN', 'ATTEMPT TO MURDER',0.75),
 ('FEMALE TEEN', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0),
 ('FEMALE TEEN', 'RAPE',0.7),
 ('FEMALE TEEN', 'CUSTODIAL RAPE',0),
 ('FEMALE TEEN', 'OTHER RAPE',0),
 ('FEMALE TEEN', 'KIDNAPPING & ABDUCTION',0.8),
 ('FEMALE TEEN', 'DACOITY',0),
 ('FEMALE TEEN', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('FEMALE TEEN', 'ROBBERY',0),
 ('FEMALE TEEN', 'BURGLARY',0),
 ('FEMALE TEEN', 'THEFT',0),
 ('FEMALE TEEN', 'AUTO THEFT',0),
 ('FEMALE TEEN', 'OTHER THEFT',0),
 ('FEMALE TEEN', 'RIOTS',0),
 ('FEMALE TEEN', 'CRIMINAL BREACH OF TRUST',0),
 ('FEMALE TEEN', 'CHEATING',0),
 ('FEMALE TEEN', 'COUNTERFIETING',0),
 ('FEMALE TEEN', 'ARSON',0),
 ('FEMALE TEEN', 'HURT/GREVIOUS HURT',0),
 ('FEMALE TEEN', 'DOWRY DEATHS',0),
 ('FEMALE TEEN', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0.6),
 ('FEMALE TEEN', 'INSULT TO MODESTY OF WOMEN',0.5),
 ('FEMALE TEEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0.3),
 ('FEMALE TEEN', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0.4),
 ('FEMALE TEEN', 'CAUSING DEATH BY NEGLIGENCE',0.4),
 ('FEMALE TEEN', 'OTHER IPC CRIMES',0),
 ('FEMALE TEEN', 'TOTAL IPC CRIMES',0),
 ('FEMALE TEEN', 'OTHER THEFTS',0),
 ('FEMALE TEEN', 'FORGERY',0),
 ('FEMALE TEEN', 'COUNTERFEITING',0),
 ('FEMALE TEEN', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('FEMALE ADULT', 'MURDER',0.7),
 ('FEMALE ADULT', 'ATTEMPT TO MURDER',0),
 ('FEMALE ADULT', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0.3),
 ('FEMALE ADULT', 'RAPE',0.9),
 ('FEMALE ADULT', 'CUSTODIAL RAPE',0.7),
 ('FEMALE ADULT', 'OTHER RAPE',0),
 ('FEMALE ADULT', 'KIDNAPPING & ABDUCTION',0.6),
 ('FEMALE ADULT', 'DACOITY',0),
 ('FEMALE ADULT', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('FEMALE ADULT', 'ROBBERY',0.5),
 ('FEMALE ADULT', 'BURGLARY',0),
 ('FEMALE ADULT', 'THEFT',0),
 ('FEMALE ADULT', 'AUTO THEFT',0),
 ('FEMALE ADULT', 'OTHER THEFT',0),
 ('FEMALE ADULT', 'RIOTS',0),
 ('FEMALE ADULT', 'CRIMINAL BREACH OF TRUST',0),
 ('FEMALE ADULT', 'CHEATING',0),
 ('FEMALE ADULT', 'COUNTERFIETING',0),
 ('FEMALE ADULT', 'ARSON',0),
 ('FEMALE ADULT', 'HURT/GREVIOUS HURT',0.55),
 ('FEMALE ADULT', 'DOWRY DEATHS',0.6),
 ('FEMALE ADULT', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0.4),
 ('FEMALE ADULT', 'INSULT TO MODESTY OF WOMEN',0.4),
 ('FEMALE ADULT', 'CRUELTY BY HUSBAND OR HIS RELATIVES',,0.3),
 ('FEMALE ADULT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('FEMALE ADULT', 'CAUSING DEATH BY NEGLIGENCE',0.4),
 ('FEMALE ADULT', 'OTHER IPC CRIMES',0),
 ('FEMALE ADULT', 'TOTAL IPC CRIMES',0.1),
 ('FEMALE ADULT', 'OTHER THEFTS',0),
 ('FEMALE ADULT', 'FORGERY',0),
 ('FEMALE ADULT', 'COUNTERFEITING',0),
 ('FEMALE ADULT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('FEMALE OLD', 'MURDER',0),
 ('FEMALE OLD', 'ATTEMPT TO MURDER',0),
 ('FEMALE OLD', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0),
 ('FEMALE OLD', 'RAPE',0.4),
 ('FEMALE OLD', 'CUSTODIAL RAPE',0.23),
 ('FEMALE OLD', 'OTHER RAPE',0.33),
 ('FEMALE OLD', 'KIDNAPPING & ABDUCTION',0.3),
 ('FEMALE OLD', 'DACOITY',0),
 ('FEMALE OLD', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('FEMALE OLD', 'ROBBERY',0),
 ('FEMALE OLD', 'BURGLARY',0),
 ('FEMALE OLD', 'THEFT',0),
 ('FEMALE OLD', 'AUTO THEFT',0),
 ('FEMALE OLD', 'OTHER THEFT',0),
 ('FEMALE OLD', 'RIOTS',0),
 ('FEMALE OLD', 'CRIMINAL BREACH OF TRUST',0),
 ('FEMALE OLD', 'CHEATING',0),
 ('FEMALE OLD', 'COUNTERFIETING',0),
 ('FEMALE OLD', 'ARSON',0),
 ('FEMALE OLD', 'HURT/GREVIOUS HURT',0),
 ('FEMALE OLD', 'DOWRY DEATHS',0),
 ('FEMALE OLD', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0.4),
 ('FEMALE OLD', 'INSULT TO MODESTY OF WOMEN',0.3),
 ('FEMALE OLD', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0.45),
 ('FEMALE OLD', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('FEMALE OLD', 'CAUSING DEATH BY NEGLIGENCE',0.7),
 ('FEMALE OLD', 'OTHER IPC CRIMES',0),
 ('FEMALE OLD', 'TOTAL IPC CRIMES',0),
 ('FEMALE OLD', 'OTHER THEFTS',0),
 ('FEMALE OLD', 'FORGERY',0),
 ('FEMALE OLD', 'COUNTERFEITING',0),
 ('FEMALE OLD', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('MALE INFANT', 'MURDER',0),
 ('MALE INFANT', 'ATTEMPT TO MURDER',0),
 ('MALE INFANT', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0),
 ('MALE INFANT', 'RAPE',0),
 ('MALE INFANT', 'CUSTODIAL RAPE',0),
 ('MALE INFANT', 'OTHER RAPE',0),
 ('MALE INFANT', 'KIDNAPPING & ABDUCTION',0),
 ('MALE INFANT', 'DACOITY',0),
 ('MALE INFANT', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('MALE INFANT', 'ROBBERY',0),
 ('MALE INFANT', 'BURGLARY',0),
 ('MALE INFANT', 'THEFT',0),
 ('MALE INFANT', 'AUTO THEFT',0),
 ('MALE INFANT', 'OTHER THEFT',0),
 ('MALE INFANT', 'RIOTS',0),
 ('MALE INFANT', 'CRIMINAL BREACH OF TRUST',0),
 ('MALE INFANT', 'CHEATING',0),
 ('MALE INFANT', 'COUNTERFIETING',0),
 ('MALE INFANT', 'ARSON',0),
 ('MALE INFANT', 'HURT/GREVIOUS HURT',0),
 ('MALE INFANT', 'DOWRY DEATHS',0),
 ('MALE INFANT', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0),
 ('MALE INFANT', 'INSULT TO MODESTY OF WOMEN',0),
 ('MALE INFANT', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0),
 ('MALE INFANT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('MALE INFANT', 'CAUSING DEATH BY NEGLIGENCE',0),
 ('MALE INFANT', 'OTHER IPC CRIMES',0),
 ('MALE INFANT', 'TOTAL IPC CRIMES',0),
 ('MALE INFANT', 'OTHER THEFTS',0),
 ('MALE INFANT', 'FORGERY',0),
 ('MALE INFANT', 'COUNTERFEITING',0),
 ('MALE INFANT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('MALE KID', 'MURDER',0.3),
 ('MALE KID', 'ATTEMPT TO MURDER',0.4),
 ('MALE KID', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0),
 ('MALE KID', 'RAPE',0.33),
 ('MALE KID', 'CUSTODIAL RAPE',0),
 ('MALE KID', 'OTHER RAPE',0),
 ('MALE KID', 'KIDNAPPING & ABDUCTION',0.4),
 ('MALE KID', 'DACOITY',0),
 ('MALE KID', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('MALE KID', 'ROBBERY',0),
 ('MALE KID', 'BURGLARY',0),
 ('MALE KID', 'THEFT',0),
 ('MALE KID', 'AUTO THEFT',0),
 ('MALE KID', 'OTHER THEFT',0),
 ('MALE KID', 'RIOTS',0),
 ('MALE KID', 'CRIMINAL BREACH OF TRUST',0),
 ('MALE KID', 'CHEATING',0.3),
 ('MALE KID', 'COUNTERFIETING',0),
 ('MALE KID', 'ARSON',0),`
 ('MALE KID', 'HURT/GREVIOUS HURT',0.4),
 ('MALE KID', 'DOWRY DEATHS',0),
 ('MALE KID', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0),
 ('MALE KID', 'INSULT TO MODESTY OF WOMEN',0),
 ('MALE KID', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0),
 ('MALE KID', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('MALE KID', 'CAUSING DEATH BY NEGLIGENCE',0),
 ('MALE KID', 'OTHER IPC CRIMES',0),
 ('MALE KID', 'TOTAL IPC CRIMES',0),
 ('MALE KID', 'OTHER THEFTS',0),
 ('MALE KID', 'FORGERY',0),
 ('MALE KID', 'COUNTERFEITING',0),
 ('MALE KID', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('MALE TEEN', 'MURDER',0.4),
 ('MALE TEEN', 'ATTEMPT TO MURDER',0.4),
 ('MALE TEEN', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0),
 ('MALE TEEN', 'RAPE',0.33),
 ('MALE TEEN', 'CUSTODIAL RAPE',0.4),
 ('MALE TEEN', 'OTHER RAPE',0),
 ('MALE TEEN', 'KIDNAPPING & ABDUCTION',0),
 ('MALE TEEN', 'DACOITY',0),
 ('MALE TEEN', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('MALE TEEN', 'ROBBERY',0),
 ('MALE TEEN', 'BURGLARY',0),
 ('MALE TEEN', 'THEFT',0),
 ('MALE TEEN', 'AUTO THEFT',0),
 ('MALE TEEN', 'OTHER THEFT',0),
 ('MALE TEEN', 'RIOTS',0),
 ('MALE TEEN', 'CRIMINAL BREACH OF TRUST',0),
 ('MALE TEEN', 'CHEATING',0),
 ('MALE TEEN', 'COUNTERFIETING',0),
 ('MALE TEEN', 'ARSON',0),
 ('MALE TEEN', 'HURT/GREVIOUS HURT',0.4),
 ('MALE TEEN', 'DOWRY DEATHS',0),
 ('MALE TEEN', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0),
 ('MALE TEEN', 'INSULT TO MODESTY OF WOMEN',0),
 ('MALE TEEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0),
 ('MALE TEEN', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('MALE TEEN', 'CAUSING DEATH BY NEGLIGENCE',0),
 ('MALE TEEN', 'OTHER IPC CRIMES',0),
 ('MALE TEEN', 'TOTAL IPC CRIMES',0),
 ('MALE TEEN', 'OTHER THEFTS',0),
 ('MALE TEEN', 'FORGERY',0),
 ('MALE TEEN', 'COUNTERFEITING',0),
 ('MALE TEEN', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('MALE ADULT', 'MURDER',0),
 ('MALE ADULT', 'ATTEMPT TO MURDER',0),
 ('MALE ADULT', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0),
 ('MALE ADULT', 'RAPE',0.3),
 ('MALE ADULT', 'CUSTODIAL RAPE',0),
 ('MALE ADULT', 'OTHER RAPE',0),
 ('MALE ADULT', 'KIDNAPPING & ABDUCTION',0.23),
 ('MALE ADULT', 'DACOITY',0),
 ('MALE ADULT', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('MALE ADULT', 'ROBBERY',0),
 ('MALE ADULT', 'BURGLARY',0),
 ('MALE ADULT', 'THEFT',0),
 ('MALE ADULT', 'AUTO THEFT',0),
 ('MALE ADULT', 'OTHER THEFT',0),
 ('MALE ADULT', 'RIOTS',0),
 ('MALE ADULT', 'CRIMINAL BREACH OF TRUST',0),
 ('MALE ADULT', 'CHEATING',0),
 ('MALE ADULT', 'COUNTERFIETING',0),
 ('MALE ADULT', 'ARSON',0),
 ('MALE ADULT', 'HURT/GREVIOUS HURT',0),
 ('MALE ADULT', 'DOWRY DEATHS',0),
 ('MALE ADULT', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0),
 ('MALE ADULT', 'INSULT TO MODESTY OF WOMEN',0),
 ('MALE ADULT', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0),
 ('MALE ADULT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('MALE ADULT', 'CAUSING DEATH BY NEGLIGENCE',0),
 ('MALE ADULT', 'OTHER IPC CRIMES',0),
 ('MALE ADULT', 'TOTAL IPC CRIMES',0),
 ('MALE ADULT', 'OTHER THEFTS',0),
 ('MALE ADULT', 'FORGERY',0),
 ('MALE ADULT', 'COUNTERFEITING',0),
 ('MALE ADULT', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0),
 ('MALE OLD', 'MURDER',0.3),
 ('MALE OLD', 'ATTEMPT TO MURDER',0.33),
 ('MALE OLD', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',0.4),
 ('MALE OLD', 'RAPE',0),
 ('MALE OLD', 'CUSTODIAL RAPE',0),
 ('MALE OLD', 'OTHER RAPE',0),
 ('MALE OLD', 'KIDNAPPING & ABDUCTION',0),
 ('MALE OLD', 'DACOITY',0),
 ('MALE OLD', 'PREPARATION AND ASSEMBLY FOR DACOITY',0),
 ('MALE OLD', 'ROBBERY',0),
 ('MALE OLD', 'BURGLARY',0),
 ('MALE OLD', 'THEFT',0),
 ('MALE OLD', 'AUTO THEFT',0),
 ('MALE OLD', 'OTHER THEFT',0),
 ('MALE OLD', 'RIOTS',0),
 ('MALE OLD', 'CRIMINAL BREACH OF TRUST',0),
 ('MALE OLD', 'CHEATING',0),
 ('MALE OLD', 'COUNTERFIETING',0),
 ('MALE OLD', 'ARSON',0),
 ('MALE OLD', 'HURT/GREVIOUS HURT',0),
 ('MALE OLD', 'DOWRY DEATHS',0),
 ('MALE OLD', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',0),
 ('MALE OLD', 'INSULT TO MODESTY OF WOMEN',0),
 ('MALE OLD', 'CRUELTY BY HUSBAND OR HIS RELATIVES',0),
 ('MALE OLD', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',0),
 ('MALE OLD', 'CAUSING DEATH BY NEGLIGENCE',0),
 ('MALE OLD', 'OTHER IPC CRIMES',0),
 ('MALE OLD', 'TOTAL IPC CRIMES',0),
 ('MALE OLD', 'OTHER THEFTS',0),
 ('MALE OLD', 'FORGERY',0),
 ('MALE OLD', 'COUNTERFEITING',0),
 ('MALE OLD', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY',0)]

In [679]:
placeWise=pd.read_csv("placeWiseProcessed.csv")

In [680]:
placeWise

,STATE/UT,YEAR,RESIDENTIAL PREMISES - Dacoity,RESIDENTIAL PREMISES - Robbery,RESIDENTIAL PREMISES - Burglary,RESIDENTIAL PREMISES - Theft,HIGHWAYS - Dacoity,HIGHWAYS - Robbery,HIGHWAYS - Burglary,HIGHWAYS - Theft,...,TOTAL - Burglary,TOTAL - Theft,RELIGIOUS PLACES_DACOITY_CASES REPORTED,RELIGIOUS PLACES_ROBBERY_CASES REPORTED,RELIGIOUS PLACES_BURGLARY_CASES REPORTED,RELIGIOUS PLACES_THEFT_CASES REPORTED,ATM_DACOITY_CASES REPORTED,ATM_ROBBERY_CASES REPORTED,ATM_BURGLARY_CASES REPORTED,ATM_THEFT_CASES REPORTED
0,ANDHRA PRADESH,2001,100,177,5158,4257,57,172,31,74,...,7.220000e+03,16751,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ARUNACHAL PRADESH,2001,9,26,99,131,0,0,0,8,...,2.480000e+02,443,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ASSAM,2001,381,191,1695,2901,46,136,7,87,...,2.423000e+03,5367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,BIHAR,2001,818,326,2486,4741,162,826,0,257,...,3.233000e+03,9701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CHHATTISGARH,2001,54,42,3336,1417,10,38,12,72,...,4.144000e+03,4812,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,LAKSHADWEEP,2014,0,0,10,671912,0,0,0,0,...,1.000000e+01,671912,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
529,PUDUCHERRY,2014,200001,1075003,7466040,2900778,252002,110002,90002,7596928,...,8.512913e+06,20538576,0.0,0.0,11002.0,95005.0,0.0,0.0,772508.0,0.0
530,TOTAL (STATES),2014,370484467,318622764,5302469296,5223603572,587281457,1243496044,39418960,2516350916,...,9.018441e+09,22747204570,573508.0,11846064.0,63915550.5,81635051.0,1875008.0,2229565.0,39470117.0,31233281.0
531,TOTAL (UTS),2014,2051945,36560944,648857341,612799725,125289838,198351620,2277027,1175780869,...,1.392349e+09,3177564805,0.0,74950.0,409027.0,2353509.0,0.0,50001.0,1169616.0,2874900.0
532,TOTAL (ALL INDIA),2014,372536412,355183708,5951326637,5836403297,712571295,1441847664,41695987,3692131785,...,1.041079e+10,25924769375,573508.0,11921014.0,64324577.5,83988560.0,1875008.0,2279566.0,40639733.0,34108181.0

In [681]:
placeWise["sum"]=placeWise.sum(axis=1)

/var/folders/50/s975vnxj44n4kkfwfjrysqqm0000gn/T/ipykernel_48589/2850029383.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  placeWise["sum"]=placeWise.sum(axis=1)

In [682]:
placeWise

,STATE/UT,YEAR,RESIDENTIAL PREMISES - Dacoity,RESIDENTIAL PREMISES - Robbery,RESIDENTIAL PREMISES - Burglary,RESIDENTIAL PREMISES - Theft,HIGHWAYS - Dacoity,HIGHWAYS - Robbery,HIGHWAYS - Burglary,HIGHWAYS - Theft,...,TOTAL - Theft,RELIGIOUS PLACES_DACOITY_CASES REPORTED,RELIGIOUS PLACES_ROBBERY_CASES REPORTED,RELIGIOUS PLACES_BURGLARY_CASES REPORTED,RELIGIOUS PLACES_THEFT_CASES REPORTED,ATM_DACOITY_CASES REPORTED,ATM_ROBBERY_CASES REPORTED,ATM_BURGLARY_CASES REPORTED,ATM_THEFT_CASES REPORTED,sum
0,ANDHRA PRADESH,2001,100,177,5158,4257,57,172,31,74,...,16751,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.162900e+04
1,ARUNACHAL PRADESH,2001,9,26,99,131,0,0,0,8,...,443,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.595000e+03
2,ASSAM,2001,381,191,1695,2901,46,136,7,87,...,5367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.001900e+04
3,BIHAR,2001,818,326,2486,4741,162,826,0,257,...,9701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.485700e+04
4,CHHATTISGARH,2001,54,42,3336,1417,10,38,12,72,...,4812,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.076300e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,LAKSHADWEEP,2014,0,0,10,671912,0,0,0,0,...,671912,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.345858e+06
529,PUDUCHERRY,2014,200001,1075003,7466040,2900778,252002,110002,90002,7596928,...,20538576,0.0,0.0,11002.0,95005.0,0.0,0.0,772508.0,0.0,6.147501e+07
530,TOTAL (STATES),2014,370484467,318622764,5302469296,5223603572,587281457,1243496044,39418960,2516350916,...,22747204570,573508.0,11846064.0,63915550.5,81635051.0,1875008.0,2229565.0,39470117.0,31233281.0,7.461201e+10
531,TOTAL (UTS),2014,2051945,36560944,648857341,612799725,125289838,198351620,2277027,1175780869,...,3177564805,0.0,74950.0,409027.0,2353509.0,0.0,50001.0,1169616.0,2874900.0,1.007114e+10
532,TOTAL (ALL INDIA),2014,372536412,355183708,5951326637,5836403297,712571295,1441847664,41695987,3692131785,...,25924769375,573508.0,11921014.0,64324577.5,83988560.0,1875008.0,2279566.0,40639733.0,34108181.0,8.468315e+10

In [927]:
crime=pd.read_csv("crimeAM.csv")

In [867]:
crime.columns

Index(['DISTRICTS', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER THEFTS', 'FORGERY',
       'COUNTERFEITING', 'sum'],
      dtype='object')

In [863]:
crime["sum"]=crime.sum(axis=1)

/var/folders/50/s975vnxj44n4kkfwfjrysqqm0000gn/T/ipykernel_48589/2071339612.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  crime["sum"]=crime.sum(axis=1)

In [850]:
crime.loc[:,"MURDER":"sum"] = crime.loc[:,"MURDER":"sum"].div(crime["sum"], axis=0)

In [868]:
crime.loc[:,"MURDER":"COUNTERFEITING"] = crime.loc[:,"MURDER":"COUNTERFEITING"].div(crime.sum(axis=1), axis=0)

/var/folders/50/s975vnxj44n4kkfwfjrysqqm0000gn/T/ipykernel_48589/1032385147.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  crime.loc[:,"MURDER":"COUNTERFEITING"] = crime.loc[:,"MURDER":"COUNTERFEITING"].div(crime.sum(axis=1), axis=0)

In [871]:
crime["SUM1"]=crime.sum(axis=1)

In [851]:
crime["SUM1"]=crime.sum(axis=1)

/var/folders/50/s975vnxj44n4kkfwfjrysqqm0000gn/T/ipykernel_48589/1128655741.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  crime["SUM1"]=crime.sum(axis=1)

In [878]:
crime["DISTRICT"]

KeyError: 'DISTRICT'

In [811]:
df_new = crime.loc[:,"ATTEMPT TO MURDER":"COUNTERFEITING"].div(crime["sum"], axis=0)

In [804]:
crime.to_csv("crimeAM.csv",index=False)

In [812]:
df_new

,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,...,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER THEFTS,FORGERY,COUNTERFEITING
0,0.007658,0.005244,0.009922,0.0,0.009922,0.037136,0.001331,0.008189,0.003898,0.001976,...,0.009480,0.003566,0.011054,0.000273,0.095159,0.000040,0.000934,0.000000,0.000000,0.000000
1,0.001090,0.003000,0.012817,0.0,0.012817,0.027720,0.001128,0.007972,0.002303,0.003670,...,0.011701,0.003675,0.008775,0.000112,0.109825,0.000016,0.002563,0.000000,0.000000,0.000000
2,0.015913,0.000838,0.002513,0.0,0.002513,0.020101,0.004188,0.000000,0.007538,0.075377,...,0.082915,0.000838,0.017588,0.001675,0.015075,0.000000,0.003350,0.000000,0.000000,0.000000
3,0.009002,0.001569,0.007012,0.0,0.007012,0.015670,0.000708,0.000000,0.002401,0.026720,...,0.179722,0.001913,0.018961,0.013202,0.043912,0.000000,0.037971,0.000000,0.000000,0.000000
4,0.007173,0.001543,0.012620,0.0,0.003813,0.008353,0.000182,0.000000,0.000636,0.053023,...,0.011077,0.001453,0.059379,0.000000,0.034865,0.000000,0.169512,0.033503,0.000000,0.000817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,0.027252,0.000757,0.004921,0.0,0.004921,0.015897,0.002271,0.000000,0.008327,0.012869,...,0.034065,0.000000,0.000757,0.000379,0.000000,0.000000,0.007949,0.008706,0.000000,0.000000
1034,0.013546,0.000903,0.012267,0.0,0.006171,0.017911,0.000828,0.000000,0.002709,0.021899,...,0.121388,0.000753,0.048916,0.000903,0.021373,0.000000,0.079922,0.002784,0.000000,0.000000
1035,0.007387,0.000573,0.009658,0.0,0.007734,0.045138,0.001166,0.001228,0.004563,0.057456,...,0.051236,0.002271,0.008758,0.001473,0.035153,0.000000,0.015489,0.003581,0.000512,0.000123
1036,0.006399,0.000679,0.007415,0.0,0.005958,0.010908,0.000938,0.000238,0.006791,0.032592,...,0.100969,0.001050,0.026949,0.008031,0.020851,0.000000,0.028699,0.011223,0.000000,0.000021
1037,0.025627,0.001636,0.014722,0.0,0.011450,0.007634,0.001636,0.000000,0.013631,0.080153,...,0.033261,0.000000,0.000000,0.000000,0.000000,0.000000,0.001636,0.011450,0.000000,0.000000

In [813]:
df_new['SUM']=df_new.sum(axis=1)

In [814]:
df_new

,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,ROBBERY,BURGLARY,...,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER THEFTS,FORGERY,COUNTERFEITING,SUM
0,0.007658,0.005244,0.009922,0.0,0.009922,0.037136,0.001331,0.008189,0.003898,0.001976,...,0.003566,0.011054,0.000273,0.095159,0.000040,0.000934,0.000000,0.000000,0.000000,0.487759
1,0.001090,0.003000,0.012817,0.0,0.012817,0.027720,0.001128,0.007972,0.002303,0.003670,...,0.003675,0.008775,0.000112,0.109825,0.000016,0.002563,0.000000,0.000000,0.000000,0.487555
2,0.015913,0.000838,0.002513,0.0,0.002513,0.020101,0.004188,0.000000,0.007538,0.075377,...,0.000838,0.017588,0.001675,0.015075,0.000000,0.003350,0.000000,0.000000,0.000000,0.487437
3,0.009002,0.001569,0.007012,0.0,0.007012,0.015670,0.000708,0.000000,0.002401,0.026720,...,0.001913,0.018961,0.013202,0.043912,0.000000,0.037971,0.000000,0.000000,0.000000,0.487735
4,0.007173,0.001543,0.012620,0.0,0.003813,0.008353,0.000182,0.000000,0.000636,0.053023,...,0.001453,0.059379,0.000000,0.034865,0.000000,0.169512,0.033503,0.000000,0.000817,0.490830
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,0.027252,0.000757,0.004921,0.0,0.004921,0.015897,0.002271,0.000000,0.008327,0.012869,...,0.000000,0.000757,0.000379,0.000000,0.000000,0.007949,0.008706,0.000000,0.000000,0.470098
1034,0.013546,0.000903,0.012267,0.0,0.006171,0.017911,0.000828,0.000000,0.002709,0.021899,...,0.000753,0.048916,0.000903,0.021373,0.000000,0.079922,0.002784,0.000000,0.000000,0.489615
1035,0.007387,0.000573,0.009658,0.0,0.007734,0.045138,0.001166,0.001228,0.004563,0.057456,...,0.002271,0.008758,0.001473,0.035153,0.000000,0.015489,0.003581,0.000512,0.000123,0.490608
1036,0.006399,0.000679,0.007415,0.0,0.005958,0.010908,0.000938,0.000238,0.006791,0.032592,...,0.001050,0.026949,0.008031,0.020851,0.000000,0.028699,0.011223,0.000000,0.000021,0.492781
1037,0.025627,0.001636,0.014722,0.0,0.011450,0.007634,0.001636,0.000000,0.013631,0.080153,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.001636,0.011450,0.000000,0.000000,0.465104

In [798]:
l1=[]
for key,value in crime.iteritems():
    l1.append(value)
l1

[0       24 PARGANAS NORTH, WEST BENGAL
 1       24 PARGANAS SOUTH, WEST BENGAL
 2       A AND N ISLANDS, A & N ISLANDS
 3             ADILABAD, ANDHRA PRADESH
 4                  ADILABAD, TELANGANA
                      ...
 1033                   WOKHA, NAGALAND
 1034                YADGIRI, KARNATAKA
 1035              YAMUNANAGAR, HARYANA
 1036             YAVATMAL, MAHARASHTRA
 1037               ZUNHEBOTO, NAGALAND
 Name: DISTRICTS, Length: 1038, dtype: object,
 0       176.071429
 1       167.142857
 2         1.071429
 3        91.571429
 4         7.214286
            ...
 1033      5.642857
 1034      9.857143
 1035     32.785714
 1036     73.642857
 1037      4.571429
 Name: MURDER, Length: 1038, dtype: float64,
 0       110.142857
 1        14.642857
 2         1.357143
 3        67.214286
 4         5.642857
            ...
 1033      5.142857
 1034     12.857143
 1035     25.785714
 1036     65.285714
 1037      3.357143
 Name: ATTEMPT TO MURDER, Length: 1038, dtype: float64,
 0       75.428571
 1       40.285714
 2        0.071429
 3       11.714286
 4        1.214286
           ...
 1033     0.142857
 1034     0.857143
 1035     2.000000
 1036     6.928571
 1037     0.214286
 Name: CULPABLE HOMICIDE NOT AMOUNTING TO MURDER, Length: 1038, dtype: float64,
 0       142.714286
 1       172.142857
 2         0.214286
 3        52.357143
 4         9.928571
            ...
 1033      0.928571
 1034     11.642857
 1035     33.714286
 1036     75.642857
 1037      1.928571
 Name: RAPE, Length: 1038, dtype: float64,
 0       0.0
 1       0.0
 2       0.0
 3       0.0
 4       0.0
        ...
 1033    0.0
 1034    0.0
 1035    0.0
 1036    0.0
 1037    0.0
 Name: CUSTODIAL RAPE, Length: 1038, dtype: float64,
 0       142.714286
 1       172.142857
 2         0.214286
 3        52.357143
 4         3.000000
            ...
 1033      0.928571
 1034      5.857143
 1035     27.000000
 1036     60.785714
 1037      1.500000
 Name: OTHER RAPE, Length: 1038, dtype: float64,
 0       534.142857
 1       372.285714
 2         1.714286
 3       117.000000
 4         6.571429
            ...
 1033      3.000000
 1034     17.000000
 1035    157.571429
 1036    111.285714
 1037      1.000000
 Name: KIDNAPPING & ABDUCTION, Length: 1038, dtype: float64,
 0       19.142857
 1       15.142857
 2        0.357143
 3        5.285714
 4        0.142857
           ...
 1033     0.428571
 1034     0.785714
 1035     4.071429
 1036     9.571429
 1037     0.214286
 Name: DACOITY, Length: 1038, dtype: float64,
 0       117.785714
 1       107.071429
 2         0.000000
 3         0.000000
 4         0.000000
            ...
 1033      0.000000
 1034      0.000000
 1035      4.285714
 1036      2.428571
 1037      0.000000
 Name: PREPARATION AND ASSEMBLY FOR DACOITY, Length: 1038, dtype: float64,
 0       56.071429
 1       30.928571
 2        0.642857
 3       17.928571
 4        0.500000
           ...
 1033     1.571429
 1034     2.571429
 1035    15.928571
 1036    69.285714
 1037     1.785714
 Name: ROBBERY, Length: 1038, dtype: float64,
 0        28.428571
 1        49.285714
 2         6.428571
 3       199.500000
 4        41.714286
            ...
 1033      2.428571
 1034     20.785714
 1035    200.571429
 1036    332.500000
 1037     10.500000
 Name: BURGLARY, Length: 1038, dtype: float64,
 0       1666.857143
 1       1403.714286
 2          8.000000
 3        310.071429
 4         36.071429
            ...
 1033      30.571429
 1034      23.285714
 1035     385.428571
 1036    1044.214286
 1037      17.142857
 Name: THEFT, Length: 1038, dtype: float64,
 0       443.500000
 1       278.571429
 2         0.571429
 3        60.071429
 4         9.714286
            ...
 1033      2.357143
 1034     10.642857
 1035    267.000000
 1036    146.214286
 1037      2.642857
 Name: AUTO THEFT, Length: 1038, dtype: float64,
 0       1223.357143
 1       1125.142857
 2          7.428571
 3        250.000000
 4          0.000000
            ...
 1033      26.571429
 1034      10.000000
 1035     105.928571
 1036     783.500000
 1037      13.000000
 Name: OTHER THEFT, Length: 1038, dtype: float64,
 0       428.214286
 1       771.928571
 2         1.214286
 3        76.714286
 4         5.642857
            ...
 1033      2.071429
 1034     72.500000
 1035      1.071429
 1036    153.857143
 1037      0.071429
 Name: RIOTS, Length: 1038, dtype: float64,
 0       99.142857
 1       12.285714
 2        0.500000
 3       24.785714
 4        3.071429
           ...
 1033     0.785714
 1034     0.285714
 1035     8.857143
 1036    24.142857
 1037     0.214286
 Name: CRIMINAL BREACH OF TRUST, Length: 1038, dtype: float64,
 0       171.714286
 1       133.071429
 2         1.642857
 3       156.142857
 4        15.928571
            ...
 1033      1.000000
 1034     10.285714
 1035     51.642857
 1036     72.785714
 1037      1.142857
 Name: CHEATING, Length: 1038, dtype: float64,
 0       10.928571
 1        3.214286
 2        0.071429
 3        2.428571
 4        0.000000
           ...
 1033     0.142857
 1034     0.214286
 1035     1.285714
 1036     2.642857
 1037     0.142857
 Name: COUNTERFIETING, Length: 1038, dtype: float64,
 0       12.071429
 1       10.714286
 2        0.785714
 3       30.357143
 4        2.642857
           ...
 1033     0.857143
 1034     3.142857
 1035     6.500000
 1036    48.357143
 1037     0.000000
 Name: ARSON, Length: 1038, dtype: float64,
 0        136.357143
 1        157.142857
 2          7.071429
 3       1341.857143
 4          8.714286
            ...
 1033       6.428571
 1034     115.214286
 1035     178.857143
 1036    1030.071429
 1037       4.357143
 Name: HURT/GREVIOUS HURT, Length: 1038, dtype: float64,
 0       51.285714
 1       49.357143
 2        0.071429
 3       14.285714
 4        1.142857
           ...
 1033     0.000000
 1034     0.714286
 1035     7.928571
 1036    10.714286
 1037     0.000000
 Name: DOWRY DEATHS, Length: 1038, dtype: float64,
 0       159.000000
 1       117.857143
 2         1.500000
 3       141.571429
 4        46.714286
            ...
 1033      0.142857
 1034     46.428571
 1035     30.571429
 1036    274.928571
 1037      0.000000
 Name: ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY, Length: 1038, dtype: float64,
 0        3.928571
 1        1.500000
 2        0.142857
 3       98.571429
 4        0.000000
           ...
 1033     0.071429
 1034     0.857143
 1035     5.142857
 1036    81.928571
 1037     0.000000
 Name: INSULT TO MODESTY OF WOMEN, Length: 1038, dtype: float64,
 0       1368.714286
 1       1475.000000
 2          1.285714
 3        327.857143
 4         27.428571
            ...
 1033       0.000000
 1034      20.285714
 1035     122.714286
 1036     212.714286
 1037       0.000000
 Name: CRUELTY BY HUSBAND OR HIS RELATIVES, Length: 1038, dtype: float64,
 0       0.571429
 1       0.214286
 2       0.000000
 3       0.000000
 4       0.000000
           ...
 1033    0.000000
 1034    0.000000
 1035    0.000000
 1036    0.000000
 1037    0.000000
 Name: IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES, Length: 1038, dtype: float64,
 0        13.428571
 1        34.428571
 2         0.285714
 3       283.500000
 4       133.357143
            ...
 1033      1.500000
 1034     75.857143
 1035     54.071429
 1036    292.785714
 1037      0.214286
 Name: CAUSING DEATH BY NEGLIGENCE, Length: 1038, dtype: float64,
 0         0.000000
 1         0.000000
 2         0.000000
 3         0.000000
 4        26.357143
            ...
 1033      1.642857
 1034      2.642857
 1035     12.500000
 1036    114.500000
 1037      1.500000
 Name: OTHER THEFTS, Length: 1038, dtype: float64,
 0       0.000000
 1       0.000000
 2       0.000000
 3       0.000000
 4       0.000000
           ...
 1033    0.000000
 1034    0.000000
 1035    1.785714
 1036    0.000000
 1037    0.000000
 Name: FORGERY, Length: 1038, dtype: float64,
 0       0.000000
 1       0.000000
 2       0.000000
 3       0.000000
 4       0.642857
           ...
 1033    0.000000
 1034    0.000000
 1035    0.428571
 1036    0.214286
 1037    0.000000
 Name: COUNTERFEITING, Length: 1038, dtype: float64,
 0       7191.714286
 1       6715.214286
 2         42.642857
 3       3733.142857
 4        393.357143
            ...
 1033      94.357143
 1034     474.571429
 1035    1745.428571
 1036    5100.928572
 1037      65.500000
 Name: sum, Length: 1038, dtype: float64]

In [790]:
crime.index.values
for key,value in crime.iteritems():
    crime

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [759]:
for i in crime.index

0       110.142857
1        14.642857
2         1.357143
3        67.214286
4         5.642857
           ...
1033      5.142857
1034     12.857143
1035     25.785714
1036     65.285714
1037      3.357143
Name: ATTEMPT TO MURDER, Length: 1038, dtype: float64
0       75.428571
1       40.285714
2        0.071429
3       11.714286
4        1.214286
          ...
1033     0.142857
1034     0.857143
1035     2.000000
1036     6.928571
1037     0.214286
Name: CULPABLE HOMICIDE NOT AMOUNTING TO MURDER, Length: 1038, dtype: float64
0       142.714286
1       172.142857
2         0.214286
3        52.357143
4         9.928571
           ...
1033      0.928571
1034     11.642857
1035     33.714286
1036     75.642857
1037      1.928571
Name: RAPE, Length: 1038, dtype: float64
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1033    0.0
1034    0.0
1035    0.0
1036    0.0
1037    0.0
Name: CUSTODIAL RAPE, Length: 1038, dtype: float64
0       142.714286
1       172.142857
2         0.214286
3        52.357143
4         3.000000
           ...
1033      0.928571
1034      5.857143
1035     27.000000
1036     60.785714
1037      1.500000
Name: OTHER RAPE, Length: 1038, dtype: float64
0       534.142857
1       372.285714
2         1.714286
3       117.000000
4         6.571429
           ...
1033      3.000000
1034     17.000000
1035    157.571429
1036    111.285714
1037      1.000000
Name: KIDNAPPING & ABDUCTION, Length: 1038, dtype: float64
0       19.142857
1       15.142857
2        0.357143
3        5.285714
4        0.142857
          ...
1033     0.428571
1034     0.785714
1035     4.071429
1036     9.571429
1037     0.214286
Name: DACOITY, Length: 1038, dtype: float64
0       117.785714
1       107.071429
2         0.000000
3         0.000000
4         0.000000
           ...
1033      0.000000
1034      0.000000
1035      4.285714
1036      2.428571
1037      0.000000
Name: PREPARATION AND ASSEMBLY FOR DACOITY, Length: 1038, dtype: float64
0       56.071429
1       30.928571
2        0.642857
3       17.928571
4        0.500000
          ...
1033     1.571429
1034     2.571429
1035    15.928571
1036    69.285714
1037     1.785714
Name: ROBBERY, Length: 1038, dtype: float64
0        28.428571
1        49.285714
2         6.428571
3       199.500000
4        41.714286
           ...
1033      2.428571
1034     20.785714
1035    200.571429
1036    332.500000
1037     10.500000
Name: BURGLARY, Length: 1038, dtype: float64
0       1666.857143
1       1403.714286
2          8.000000
3        310.071429
4         36.071429
           ...
1033      30.571429
1034      23.285714
1035     385.428571
1036    1044.214286
1037      17.142857
Name: THEFT, Length: 1038, dtype: float64
0       443.500000
1       278.571429
2         0.571429
3        60.071429
4         9.714286
           ...
1033      2.357143
1034     10.642857
1035    267.000000
1036    146.214286
1037      2.642857
Name: AUTO THEFT, Length: 1038, dtype: float64
0       1223.357143
1       1125.142857
2          7.428571
3        250.000000
4          0.000000
           ...
1033      26.571429
1034      10.000000
1035     105.928571
1036     783.500000
1037      13.000000
Name: OTHER THEFT, Length: 1038, dtype: float64
0       428.214286
1       771.928571
2         1.214286
3        76.714286
4         5.642857
           ...
1033      2.071429
1034     72.500000
1035      1.071429
1036    153.857143
1037      0.071429
Name: RIOTS, Length: 1038, dtype: float64
0       99.142857
1       12.285714
2        0.500000
3       24.785714
4        3.071429
          ...
1033     0.785714
1034     0.285714
1035     8.857143
1036    24.142857
1037     0.214286
Name: CRIMINAL BREACH OF TRUST, Length: 1038, dtype: float64
0       171.714286
1       133.071429
2         1.642857
3       156.142857
4        15.928571
           ...
1033      1.000000
1034     10.285714
1035     51.642857
1036     72.785714
1037      1.142857
Name: CHEATING, Length: 1038, dtype: float64
0       10.928571
1        3.214286
2        0.071429
3        2.428571
4        0.000000
          ...
1033     0.142857
1034     0.214286
1035     1.285714
1036     2.642857
1037     0.142857
Name: COUNTERFIETING, Length: 1038, dtype: float64
0       12.071429
1       10.714286
2        0.785714
3       30.357143
4        2.642857
          ...
1033     0.857143
1034     3.142857
1035     6.500000
1036    48.357143
1037     0.000000
Name: ARSON, Length: 1038, dtype: float64
0        136.357143
1        157.142857
2          7.071429
3       1341.857143
4          8.714286
           ...
1033       6.428571
1034     115.214286
1035     178.857143
1036    1030.071429
1037       4.357143
Name: HURT/GREVIOUS HURT, Length: 1038, dtype: float64
0       51.285714
1       49.357143
2        0.071429
3       14.285714
4        1.142857
          ...
1033     0.000000
1034     0.714286
1035     7.928571
1036    10.714286
1037     0.000000
Name: DOWRY DEATHS, Length: 1038, dtype: float64
0       159.000000
1       117.857143
2         1.500000
3       141.571429
4        46.714286
           ...
1033      0.142857
1034     46.428571
1035     30.571429
1036    274.928571
1037      0.000000
Name: ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY, Length: 1038, dtype: float64
0        3.928571
1        1.500000
2        0.142857
3       98.571429
4        0.000000
          ...
1033     0.071429
1034     0.857143
1035     5.142857
1036    81.928571
1037     0.000000
Name: INSULT TO MODESTY OF WOMEN, Length: 1038, dtype: float64
0       1368.714286
1       1475.000000
2          1.285714
3        327.857143
4         27.428571
           ...
1033       0.000000
1034      20.285714
1035     122.714286
1036     212.714286
1037       0.000000
Name: CRUELTY BY HUSBAND OR HIS RELATIVES, Length: 1038, dtype: float64
0       0.571429
1       0.214286
2       0.000000
3       0.000000
4       0.000000
          ...
1033    0.000000
1034    0.000000
1035    0.000000
1036    0.000000
1037    0.000000
Name: IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES, Length: 1038, dtype: float64
0        13.428571
1        34.428571
2         0.285714
3       283.500000
4       133.357143
           ...
1033      1.500000
1034     75.857143
1035     54.071429
1036    292.785714
1037      0.214286
Name: CAUSING DEATH BY NEGLIGENCE, Length: 1038, dtype: float64
0         0.000000
1         0.000000
2         0.000000
3         0.000000
4        26.357143
           ...
1033      1.642857
1034      2.642857
1035     12.500000
1036    114.500000
1037      1.500000
Name: OTHER THEFTS, Length: 1038, dtype: float64
0       0.000000
1       0.000000
2       0.000000
3       0.000000
4       0.000000
          ...
1033    0.000000
1034    0.000000
1035    1.785714
1036    0.000000
1037    0.000000
Name: FORGERY, Length: 1038, dtype: float64
0       0.000000
1       0.000000
2       0.000000
3       0.000000
4       0.642857
          ...
1033    0.000000
1034    0.000000
1035    0.428571
1036    0.214286
1037    0.000000
Name: COUNTERFEITING, Length: 1038, dtype: float64
0       7191.714286
1       6715.214286
2         42.642857
3       3733.142857
4        393.357143
           ...
1033      94.357143
1034     474.571429
1035    1745.428571
1036    5100.928572
1037      65.500000
Name: sum, Length: 1038, dtype: float64

In [758]:
crime.columns[2:30]

Index(['ATTEMPT TO MURDER', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER',
       'RAPE', 'CUSTODIAL RAPE', 'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'DACOITY', 'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY',
       'BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFT', 'RIOTS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'COUNTERFIETING', 'ARSON',
       'HURT/GREVIOUS HURT', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER THEFTS', 'FORGERY',
       'COUNTERFEITING'],
      dtype='object')

In [713]:
val

array([[0, 2014, 372536412, 355183708, 5951326637, 5836403297, 712571295,
        1441847664, 41695987, 3692131785, 25001, 990177, 17003, 88434161,
        7425635, 39725113, 5630703, 827422144, 74641404, 21643196,
        307620266, 41585474, 93851882, 153205917, 2040945884, 2879882167,
        1387344742, 1330073662, 1958588656, 12437413606, 2650844887,
        3356870017, 10410789447.0, 25924769375, 573508.0, 11921014.0,
        64324577.5, 83988560.0, 1875008.0, 2279566.0, 40639733.0,
        34108181.0, 84683149465.5]], dtype=object)

In [714]:
nrm=val[0][-1]

In [715]:
val[0][0]=0

In [716]:
nrm

84683149465.5

In [717]:
fin=val/nrm

In [718]:
fin

array([[0.0, 2.3782771575123167e-08, 0.004399179935457782,
        0.0041942666308685435, 0.07027757794275916, 0.06892047985742142,
        0.008414558262152287, 0.01702638214450692, 0.0004923764321848585,
        0.043599367858940793, 2.952299265887062e-07,
        1.1692727611688546e-05, 2.00783746321658e-07,
        0.0010442946626120484, 8.768727954579926e-05,
        0.00046910292367177545, 6.649142167644525e-05,
        0.009770800321226746, 0.0008814197921442327,
        0.0002555785435072589, 0.0036326030378136184,
        0.0004910714145904784, 0.0011082710384813373,
        0.0018091664984946768, 0.024100968101469625, 0.03400773572047255,
        0.016382772142469804, 0.01570647372464428, 0.023128434267763398,
        0.14686999343437285, 0.031303097531581024, 0.03964035393331222,
        0.12293814664086586, 0.30613846483782203, 6.7723980935976846e-06,
        0.00014077197264441177, 0.0007595912280778586,
        0.0009917977842122774, 2.214145330959709e-05,
        2.691876736266992e-05, 0.000479903419470206,
        0.0004027741199433744, 1.0]], dtype=object)

In [727]:
len(placeWise.columns[2:])

41

In [722]:
fin=np.delete(fin,0)

In [726]:
len(fin)

41

In [ ]:
l1=[]
for i in placeWise,fin:

In [728]:
for i in range(41):
    print(placeWise.columns[2:][i], fin[i])

RESIDENTIAL PREMISES - Dacoity 0.004399179935457782
RESIDENTIAL PREMISES - Robbery 0.0041942666308685435
RESIDENTIAL PREMISES - Burglary 0.07027757794275916
RESIDENTIAL PREMISES - Theft 0.06892047985742142
HIGHWAYS - Dacoity 0.008414558262152287
HIGHWAYS - Robbery 0.01702638214450692
HIGHWAYS - Burglary 0.0004923764321848585
HIGHWAYS - Theft 0.043599367858940793
RIVER and SEA - Dacoity 2.952299265887062e-07
RIVER and SEA - Robbery 1.1692727611688546e-05
RIVER and SEA - Burglary 2.00783746321658e-07
RIVER and SEA - Theft 0.0010442946626120484
RAILWAYS - Dacoity 8.768727954579926e-05
RAILWAYS - Robbery 0.00046910292367177545
RAILWAYS - Burglary 6.649142167644525e-05
RAILWAYS - Theft 0.009770800321226746
BANKS - Dacoity 0.0008814197921442327
BANKS - Robbery 0.0002555785435072589
BANKS - Burglary 0.0036326030378136184
BANKS - Theft 0.0004910714145904784
COMMERCIAL ESTABLISHMENTS - Dacoity 0.0011082710384813373
COMMERCIAL ESTABLISHMENTS - Robbery 0.0018091664984946768
COMMERCIAL ESTABLISHMENTS - Burglary 0.024100968101469625
COMMERCIAL ESTABLISHMENTS - Theft 0.03400773572047255
OTHER PLACES - Dacoity 0.016382772142469804
OTHER PLACES - Robbery 0.01570647372464428
OTHER PLACES - Burglary 0.023128434267763398
OTHER PLACES - Theft 0.14686999343437285
TOTAL - Dacoity 0.031303097531581024
TOTAL - Robbery 0.03964035393331222
TOTAL - Burglary 0.12293814664086586
TOTAL - Theft 0.30613846483782203
RELIGIOUS PLACES_DACOITY_CASES REPORTED 6.7723980935976846e-06
RELIGIOUS PLACES_ROBBERY_CASES REPORTED 0.00014077197264441177
RELIGIOUS PLACES_BURGLARY_CASES REPORTED 0.0007595912280778586
RELIGIOUS PLACES_THEFT_CASES REPORTED 0.0009917977842122774
ATM_DACOITY_CASES REPORTED 2.214145330959709e-05
ATM_ROBBERY_CASES REPORTED 2.691876736266992e-05
ATM_BURGLARY_CASES REPORTED 0.000479903419470206
ATM_THEFT_CASES REPORTED 0.0004027741199433744
sum 1.0

In [729]:
crime

array(['MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE',
       'CUSTODIAL RAPE', 'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'DACOITY', 'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY',
       'BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFT', 'RIOTS',
       'CRIMINAL BREACH OF TRUST', 'CHEATING', 'COUNTERFIETING', 'ARSON',
       'HURT/GREVIOUS HURT', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN',
       'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES',
       'TOTAL IPC CRIMES', 'OTHER THEFTS', 'FORGERY', 'COUNTERFEITING',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRY'], dtype='<U51')

In [734]:
dfF

,STATE/UT,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,...,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES,OTHER THEFTS,FORGERY,COUNTERFEITING,IMPORTATION OF GIRLS FROM FOREIGN COUNTRY
0,"ADILABAD, ANDHRA PRADESH",101,60,17,50,0,50,92,9,0,...,34.0,175,0.0,181,1518,4154,0.0,0.0,0.0,0.0
1,"ANANTAPUR, ANDHRA PRADESH",151,125,1,23,0,23,106,8,0,...,24.0,154,0.0,270,754,4125,0.0,0.0,0.0,0.0
2,"CHITTOOR, ANDHRA PRADESH",101,57,2,27,0,27,118,4,0,...,83.0,186,0.0,404,1262,5818,0.0,0.0,0.0,0.0
3,"CUDDAPAH, ANDHRA PRADESH",80,53,1,20,0,20,50,1,0,...,38.0,57,0.0,233,1181,3140,0.0,0.0,0.0,0.0
4,"EAST GODAVARI, ANDHRA PRADESH",82,67,1,23,0,23,98,4,0,...,58.0,247,0.0,431,2313,6507,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10673,"LAKSHADWEEP, LAKSHADWEEP",0,0,0,3,0,1,0,0,0,...,0.0,0,0.0,1,30,81,15.0,2.0,0.0,0.0
10674,"TOTAL, LAKSHADWEEP",0,0,0,3,0,1,0,0,0,...,0.0,0,0.0,1,30,81,15.0,2.0,0.0,0.0
10675,"KARAIKAL, PUDUCHERRY",6,1,0,9,0,3,2,2,1,...,0.0,1,0.0,292,322,671,22.0,5.0,0.0,0.0
10676,"PUDUCHERRY, PUDUCHERRY",19,14,3,21,1,8,24,4,4,...,0.0,3,0.0,1317,1014,2913,117.0,8.0,0.0,0.0
10677,"TOTAL, PUDUCHERRY",25,15,3,30,1,11,26,6,5,...,0.0,4,0.0,1609,1336,3584,139.0,13.0,0.0,0.0

In [881]:
crime

,DISTRICTS,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,...,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER THEFTS,FORGERY,COUNTERFEITING,sum
0,"24 PARGANAS NORTH, WEST BENGAL",176.071429,110.142857,75.428571,142.714286,0.0,142.714286,534.142857,19.142857,117.785714,...,51.285714,159.000000,3.928571,1368.714286,0.571429,13.428571,0.000000,0.000000,0.000000,7191.714286
1,"24 PARGANAS SOUTH, WEST BENGAL",167.142857,14.642857,40.285714,172.142857,0.0,172.142857,372.285714,15.142857,107.071429,...,49.357143,117.857143,1.500000,1475.000000,0.214286,34.428571,0.000000,0.000000,0.000000,6715.214286
2,"A AND N ISLANDS, A & N ISLANDS",1.071429,1.357143,0.071429,0.214286,0.0,0.214286,1.714286,0.357143,0.000000,...,0.071429,1.500000,0.142857,1.285714,0.000000,0.285714,0.000000,0.000000,0.000000,42.642857
3,"ADILABAD, ANDHRA PRADESH",91.571429,67.214286,11.714286,52.357143,0.0,52.357143,117.000000,5.285714,0.000000,...,14.285714,141.571429,98.571429,327.857143,0.000000,283.500000,0.000000,0.000000,0.000000,3733.142857
4,"ADILABAD, TELANGANA",7.214286,5.642857,1.214286,9.928571,0.0,3.000000,6.571429,0.142857,0.000000,...,1.142857,46.714286,0.000000,27.428571,0.000000,133.357143,26.357143,0.000000,0.642857,393.357143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,"WOKHA, NAGALAND",5.642857,5.142857,0.142857,0.928571,0.0,0.928571,3.000000,0.428571,0.000000,...,0.000000,0.142857,0.071429,0.000000,0.000000,1.500000,1.642857,0.000000,0.000000,94.357143
1034,"YADGIRI, KARNATAKA",9.857143,12.857143,0.857143,11.642857,0.0,5.857143,17.000000,0.785714,0.000000,...,0.714286,46.428571,0.857143,20.285714,0.000000,75.857143,2.642857,0.000000,0.000000,474.571429
1035,"YAMUNANAGAR, HARYANA",32.785714,25.785714,2.000000,33.714286,0.0,27.000000,157.571429,4.071429,4.285714,...,7.928571,30.571429,5.142857,122.714286,0.000000,54.071429,12.500000,1.785714,0.428571,1745.428571
1036,"YAVATMAL, MAHARASHTRA",73.642857,65.285714,6.928571,75.642857,0.0,60.785714,111.285714,9.571429,2.428571,...,10.714286,274.928571,81.928571,212.714286,0.000000,292.785714,114.500000,0.000000,0.214286,5100.928572
1037,"ZUNHEBOTO, NAGALAND",4.571429,3.357143,0.214286,1.928571,0.0,1.500000,1.000000,0.214286,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.214286,1.500000,0.000000,0.000000,65.500000

In [891]:
s = sum(crime.values[0][2:-1])

In [892]:
l = [i/s for i in crime.values[0][2:-1]]

In [920]:
crime._set_value()

TypeError: _set_value() missing 3 required positional arguments: 'index', 'col', and 'value'

In [936]:
l2=list(crime.columns[1:])
l3=[]
dummy=crime.copy(deep=True)
dummy

,DISTRICTS,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,DACOITY,PREPARATION AND ASSEMBLY FOR DACOITY,...,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER THEFTS,FORGERY,COUNTERFEITING,sum
0,"24 PARGANAS NORTH, WEST BENGAL",176.071429,110.142857,75.428571,142.714286,0.0,142.714286,534.142857,19.142857,117.785714,...,51.285714,159.000000,3.928571,1368.714286,0.571429,13.428571,0.000000,0.000000,0.000000,7191.714286
1,"24 PARGANAS SOUTH, WEST BENGAL",167.142857,14.642857,40.285714,172.142857,0.0,172.142857,372.285714,15.142857,107.071429,...,49.357143,117.857143,1.500000,1475.000000,0.214286,34.428571,0.000000,0.000000,0.000000,6715.214286
2,"A AND N ISLANDS, A & N ISLANDS",1.071429,1.357143,0.071429,0.214286,0.0,0.214286,1.714286,0.357143,0.000000,...,0.071429,1.500000,0.142857,1.285714,0.000000,0.285714,0.000000,0.000000,0.000000,42.642857
3,"ADILABAD, ANDHRA PRADESH",91.571429,67.214286,11.714286,52.357143,0.0,52.357143,117.000000,5.285714,0.000000,...,14.285714,141.571429,98.571429,327.857143,0.000000,283.500000,0.000000,0.000000,0.000000,3733.142857
4,"ADILABAD, TELANGANA",7.214286,5.642857,1.214286,9.928571,0.0,3.000000,6.571429,0.142857,0.000000,...,1.142857,46.714286,0.000000,27.428571,0.000000,133.357143,26.357143,0.000000,0.642857,393.357143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,"WOKHA, NAGALAND",5.642857,5.142857,0.142857,0.928571,0.0,0.928571,3.000000,0.428571,0.000000,...,0.000000,0.142857,0.071429,0.000000,0.000000,1.500000,1.642857,0.000000,0.000000,94.357143
1034,"YADGIRI, KARNATAKA",9.857143,12.857143,0.857143,11.642857,0.0,5.857143,17.000000,0.785714,0.000000,...,0.714286,46.428571,0.857143,20.285714,0.000000,75.857143,2.642857,0.000000,0.000000,474.571429
1035,"YAMUNANAGAR, HARYANA",32.785714,25.785714,2.000000,33.714286,0.0,27.000000,157.571429,4.071429,4.285714,...,7.928571,30.571429,5.142857,122.714286,0.000000,54.071429,12.500000,1.785714,0.428571,1745.428571
1036,"YAVATMAL, MAHARASHTRA",73.642857,65.285714,6.928571,75.642857,0.0,60.785714,111.285714,9.571429,2.428571,...,10.714286,274.928571,81.928571,212.714286,0.000000,292.785714,114.500000,0.000000,0.214286,5100.928572
1037,"ZUNHEBOTO, NAGALAND",4.571429,3.357143,0.214286,1.928571,0.0,1.500000,1.000000,0.214286,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.214286,1.500000,0.000000,0.000000,65.500000

In [937]:
num=len(list(crime.iterrows()))
for i in range(num):
    l4=[]
    s=0
    s=sum(crime.values[i][2:-1])
    for j in l2:
        l4.append(dummy.loc[i].at[j]/s)
    l3.append(l4)

/var/folders/50/s975vnxj44n4kkfwfjrysqqm0000gn/T/ipykernel_48589/2182979614.py:7: RuntimeWarning: invalid value encountered in double_scalars
  l4.append(dummy.loc[i].at[j]/s)

In [941]:
for i in range(num):
    for j in l2:
        crime.loc[i,j]=l3[i][l2.index(j)]

In [943]:
crime.to_csv("FINAL.csv",index=False)

In [896]:
crime.values[0][2:-1] = l

In [897]:
crime.values[0]

array(['24 PARGANAS NORTH, WEST BENGAL', 176.0714286, 110.1428571,
       75.42857143, 142.7142857, 0.0, 142.7142857, 534.1428571,
       19.14285714, 117.7857143, 56.07142857, 28.42857143, 1666.857143,
       443.5, 1223.357143, 428.2142857, 99.14285714, 171.7142857,
       10.92857143, 12.07142857, 136.3571429, 51.28571429, 159.0,
       3.928571429, 1368.714286, 0.571428571, 13.42857143, 0.0, 0.0, 0.0,
       7191.714286230001], dtype=object)